/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Tier1ProxyView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * AccountData is a piece of global state that a validator signs and broadcasts to the network.  It is essentially the data that a validator wants to share with the network. All the nodes in the network are collecting the account data broadcasted by the validators. Since the number of the validators is bounded and their identity is known (and the maximal size of allowed AccountData is bounded) the global state that is distributed in the form of AccountData is bounded as well. Find more information in the docs [here](https://github.com/near/nearcore/blob/560f7fc8f4b3106e0d5d46050688610b1f104ac6/chain/client/src/client.rs#L2232)
 *
 * @param accountKey Account key of the validator signing this AccountData.
 * @param peerId ID of the node that handles the account key (aka validator key).
 * @param proxies Proxy nodes that are directly connected to the validator node (this list may include the validator node itself). TIER1 nodes should connect to one of the proxies to sent TIER1 messages to the validator.
 * @param timestamp UTC timestamp of when the AccountData has been signed.
 */


data class AccountDataView (

    /* Account key of the validator signing this AccountData. */
    @Json(name = "account_key")
    val accountKey: kotlin.String,

    /* ID of the node that handles the account key (aka validator key). */
    @Json(name = "peer_id")
    val peerId: kotlin.String,

    /* Proxy nodes that are directly connected to the validator node (this list may include the validator node itself). TIER1 nodes should connect to one of the proxies to sent TIER1 messages to the validator. */
    @Json(name = "proxies")
    val proxies: kotlin.collections.List<Tier1ProxyView>,

    /* UTC timestamp of when the AccountData has been signed. */
    @Json(name = "timestamp")
    val timestamp: kotlin.String

) {


}

