/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The structure describes configuration for creation of new accounts.
 *
 * @param minAllowedTopLevelAccountLength The minimum length of the top-level account ID that is allowed to be created by any account.
 * @param registrarAccountId The account ID of the account registrar. This account ID allowed to create top-level accounts of any valid length.
 */


data class AccountCreationConfigView (

    /* The minimum length of the top-level account ID that is allowed to be created by any account. */
    @Json(name = "min_allowed_top_level_account_length")
    val minAllowedTopLevelAccountLength: kotlin.Int,

    /* The account ID of the account registrar. This account ID allowed to create top-level accounts of any valid length. */
    @Json(name = "registrar_account_id")
    val registrarAccountId: kotlin.String

) {


}

