/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param limit 
 * @param totalNumberOfBytes 
 */


data class ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded (

    @Json(name = "limit")
    val limit: kotlin.Int,

    @Json(name = "total_number_of_bytes")
    val totalNumberOfBytes: kotlin.Int

) {


}

