/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionViewOneOf10UseGlobalContract

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param useGlobalContract 
 */


data class ActionViewOneOf10 (

    @Json(name = "UseGlobalContract")
    val useGlobalContract: ActionViewOneOf10UseGlobalContract

) {


}

