/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionViewOneOfDeployContract

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deployGlobalContract 
 */


data class ActionViewOneOf8 (

    @Json(name = "DeployGlobalContract")
    val deployGlobalContract: ActionViewOneOfDeployContract

) {


}

