/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The number of actions exceeded the given limit.
 *
 * @param totalNumberOfActionsExceeded 
 */


data class ActionsValidationErrorOneOf1 (

    @Json(name = "TotalNumberOfActionsExceeded")
    val totalNumberOfActionsExceeded: ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded

) {


}

