/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param protocolFeature 
 * @param version 
 */


data class ActionsValidationErrorOneOf9UnsupportedProtocolFeature (

    @Json(name = "protocol_feature")
    val protocolFeature: kotlin.String,

    @Json(name = "version")
    val version: kotlin.Int

) {


}

