/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionViewOneOf5DeleteKey
import org.openapitools.client.models.ActionsValidationErrorOneOf
import org.openapitools.client.models.ActionsValidationErrorOneOf1
import org.openapitools.client.models.ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf2
import org.openapitools.client.models.ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf3
import org.openapitools.client.models.ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf4
import org.openapitools.client.models.ActionsValidationErrorOneOf4InvalidAccountId
import org.openapitools.client.models.ActionsValidationErrorOneOf5
import org.openapitools.client.models.ActionsValidationErrorOneOf5ContractSizeExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf6
import org.openapitools.client.models.ActionsValidationErrorOneOf7
import org.openapitools.client.models.ActionsValidationErrorOneOf8
import org.openapitools.client.models.ActionsValidationErrorOneOf9
import org.openapitools.client.models.ActionsValidationErrorOneOf9UnsupportedProtocolFeature
import org.openapitools.client.models.ActionsValidationErrorOneOfTotalPrepaidGasExceeded

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Describes the error for validating a list of actions.
 *
 * @param totalPrepaidGasExceeded 
 * @param totalNumberOfActionsExceeded 
 * @param addKeyMethodNamesNumberOfBytesExceeded 
 * @param addKeyMethodNameLengthExceeded 
 * @param invalidAccountId 
 * @param contractSizeExceeded 
 * @param functionCallMethodNameLengthExceeded 
 * @param functionCallArgumentsLengthExceeded 
 * @param unsuitableStakingKey 
 * @param unsupportedProtocolFeature 
 */


data class ActionsValidationError (

    @Json(name = "TotalPrepaidGasExceeded")
    val totalPrepaidGasExceeded: ActionsValidationErrorOneOfTotalPrepaidGasExceeded,

    @Json(name = "TotalNumberOfActionsExceeded")
    val totalNumberOfActionsExceeded: ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded,

    @Json(name = "AddKeyMethodNamesNumberOfBytesExceeded")
    val addKeyMethodNamesNumberOfBytesExceeded: ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded,

    @Json(name = "AddKeyMethodNameLengthExceeded")
    val addKeyMethodNameLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded,

    @Json(name = "InvalidAccountId")
    val invalidAccountId: ActionsValidationErrorOneOf4InvalidAccountId,

    @Json(name = "ContractSizeExceeded")
    val contractSizeExceeded: ActionsValidationErrorOneOf5ContractSizeExceeded,

    @Json(name = "FunctionCallMethodNameLengthExceeded")
    val functionCallMethodNameLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded,

    @Json(name = "FunctionCallArgumentsLengthExceeded")
    val functionCallArgumentsLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded,

    @Json(name = "UnsuitableStakingKey")
    val unsuitableStakingKey: ActionViewOneOf5DeleteKey,

    @Json(name = "UnsupportedProtocolFeature")
    val unsupportedProtocolFeature: ActionsValidationErrorOneOf9UnsupportedProtocolFeature

) {


}

