/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionErrorKindOneOf3CreateAccountNotAllowed

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A newly created account must be under a namespace of the creator account
 *
 * @param createAccountNotAllowed 
 */


data class ActionErrorKindOneOf3 (

    @Json(name = "CreateAccountNotAllowed")
    val createAccountNotAllowed: ActionErrorKindOneOf3CreateAccountNotAllowed

) {


}

