/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionErrorKindOneOf18DelegateActionInvalidNonce

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * DelegateAction nonce must be greater sender[public_key].nonce
 *
 * @param delegateActionInvalidNonce 
 */


data class ActionErrorKindOneOf18 (

    @Json(name = "DelegateActionInvalidNonce")
    val delegateActionInvalidNonce: ActionErrorKindOneOf18DelegateActionInvalidNonce

) {


}

