/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccessKeyView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessKey 
 * @param publicKey 
 */


data class ActionViewOneOf4AddKey (

    @Json(name = "access_key")
    val accessKey: AccessKeyView,

    @Json(name = "public_key")
    val publicKey: kotlin.String

) {


}

