/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Error occurs when a `CreateAccount` action is called on a NEAR-implicit or ETH-implicit account. See NEAR-implicit account creation NEP: <https://github.com/nearprotocol/NEPs/pull/71>. Also, see ETH-implicit account creation NEP: <https://github.com/near/NEPs/issues/518>.  TODO(#8598): This error is named very poorly. A better name would be `OnlyNamedAccountCreationAllowed`.
 *
 * @param onlyImplicitAccountCreationAllowed 
 */


data class ActionErrorKindOneOf14 (

    @Json(name = "OnlyImplicitAccountCreationAllowed")
    val onlyImplicitAccountCreationAllowed: ActionErrorKindOneOfAccountAlreadyExists

) {


}

