/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accountId An account which needs balance
 * @param amount Balance required to complete an action.
 */


data class ActionErrorKindOneOf8LackBalanceForState (

    /* An account which needs balance */
    @Json(name = "account_id")
    val accountId: kotlin.String,

    /* Balance required to complete an action. */
    @Json(name = "amount")
    val amount: kotlin.String

) {


}

