/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Happens when TX receiver_id doesn't exist (but action is not Action::CreateAccount)
 *
 * @param accountDoesNotExist 
 */


data class ActionErrorKindOneOf1 (

    @Json(name = "AccountDoesNotExist")
    val accountDoesNotExist: ActionErrorKindOneOfAccountAlreadyExists

) {


}

