/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionErrorKindOneOf5DeleteKeyDoesNotExist

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The public key is already used for an existing access key
 *
 * @param addKeyAlreadyExists 
 */


data class ActionErrorKindOneOf6 (

    @Json(name = "AddKeyAlreadyExists")
    val addKeyAlreadyExists: ActionErrorKindOneOf5DeleteKeyDoesNotExist

) {


}

