/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FunctionCallError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An error occurred during a `FunctionCall` Action, parameter is debug message.
 *
 * @param functionCallError 
 */


data class ActionErrorKindOneOf12 (

    @Json(name = "FunctionCallError")
    val functionCallError: FunctionCallError

) {


}

