/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param length 
 * @param limit 
 */


data class ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded (

    @Json(name = "length")
    val length: kotlin.Int,

    @Json(name = "limit")
    val limit: kotlin.Int

) {


}

