/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccessKey

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An action that adds key with public key associated
 *
 * @param accessKey An access key with the permission
 * @param publicKey A public key which will be associated with an access_key
 */


data class AddKeyAction (

    /* An access key with the permission */
    @Json(name = "access_key")
    val accessKey: AccessKey,

    /* A public key which will be associated with an access_key */
    @Json(name = "public_key")
    val publicKey: kotlin.String

) {


}

