/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A part of a state for the current head of a light client. More info [here](https://nomicon.io/ChainSpec/LightClient).
 *
 * @param blockMerkleRoot The merkle root of all the block hashes
 * @param epochId The epoch to which the block that is the current known head belongs
 * @param height 
 * @param nextBpHash The hash of the block producers set for the next epoch
 * @param nextEpochId The epoch that will follow the current epoch
 * @param outcomeRoot 
 * @param prevStateRoot 
 * @param timestamp Legacy json number. Should not be used.
 * @param timestampNanosec 
 */


data class BlockHeaderInnerLiteView (

    /* The merkle root of all the block hashes */
    @Json(name = "block_merkle_root")
    val blockMerkleRoot: kotlin.String,

    /* The epoch to which the block that is the current known head belongs */
    @Json(name = "epoch_id")
    val epochId: kotlin.String,

    @Json(name = "height")
    val height: kotlin.Int,

    /* The hash of the block producers set for the next epoch */
    @Json(name = "next_bp_hash")
    val nextBpHash: kotlin.String,

    /* The epoch that will follow the current epoch */
    @Json(name = "next_epoch_id")
    val nextEpochId: kotlin.String,

    @Json(name = "outcome_root")
    val outcomeRoot: kotlin.String,

    @Json(name = "prev_state_root")
    val prevStateRoot: kotlin.String,

    /* Legacy json number. Should not be used. */
    @Json(name = "timestamp")
    val timestamp: kotlin.Int,

    @Json(name = "timestamp_nanosec")
    val timestampNanosec: kotlin.String

) {


}

