/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * URIs for the Chunk Distribution Network feature.
 *
 * @param get URI for pulling chunks from the stream.
 * @param set URI for publishing chunks to the stream.
 */


data class ChunkDistributionUris (

    /* URI for pulling chunks from the stream. */
    @Json(name = "get")
    val get: kotlin.String,

    /* URI for publishing chunks to the stream. */
    @Json(name = "set")
    val set: kotlin.String

) {


}

