/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ExternalStorageLocation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Configures the external storage used by the archival node.
 *
 * @param storage The storage to persist the archival data.
 * @param credentialsFile Location of a json file with credentials allowing access to the bucket.
 */


data class CloudStorageConfig (

    /* The storage to persist the archival data. */
    @Json(name = "storage")
    val storage: ExternalStorageLocation,

    /* Location of a json file with credentials allowing access to the bucket. */
    @Json(name = "credentials_file")
    val credentialsFile: kotlin.String? = null

) {


}

