/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Stores the congestion level of a shard. More info about congestion [here](https://near.github.io/nearcore/architecture/how/receipt-congestion.html?highlight=congestion#receipt-congestion)
 *
 * @param allowedShard 
 * @param bufferedReceiptsGas 
 * @param delayedReceiptsGas 
 * @param receiptBytes 
 */


data class CongestionInfoView (

    @Json(name = "allowed_shard")
    val allowedShard: kotlin.Int,

    @Json(name = "buffered_receipts_gas")
    val bufferedReceiptsGas: kotlin.String,

    @Json(name = "delayed_receipts_gas")
    val delayedReceiptsGas: kotlin.String,

    @Json(name = "receipt_bytes")
    val receiptBytes: kotlin.Int

) {


}

