/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A view of the contract code.
 *
 * @param codeBase64 
 * @param hash 
 */


data class ContractCodeView (

    @Json(name = "code_base64")
    val codeBase64: kotlin.String,

    @Json(name = "hash")
    val hash: kotlin.String

) {


}

