/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GlobalContractDeployMode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Deploy global contract action
 *
 * @param code WebAssembly binary
 * @param deployMode 
 */


data class DeployGlobalContractAction (

    /* WebAssembly binary */
    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "deploy_mode")
    val deployMode: GlobalContractDeployMode

) {


}

