/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nanos 
 * @param secs 
 */


data class DurationAsStdSchemaProvider (

    @Json(name = "nanos")
    val nanos: kotlin.Int,

    @Json(name = "secs")
    val secs: kotlin.Long

) {


}

