/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CostGasUsed

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param version 
 * @param gasProfile 
 */


data class ExecutionMetadataView (

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "gas_profile")
    val gasProfile: kotlin.collections.List<CostGasUsed>? = null

) {


}

