/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ExternalStorageLocation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param location Location of state parts.
 * @param externalStorageFallbackThreshold The number of attempts the node will make to obtain a part from peers in the network before it fetches from external storage.
 * @param numConcurrentRequests When fetching state parts from external storage, throttle fetch requests to this many concurrent requests.
 * @param numConcurrentRequestsDuringCatchup During catchup, the node will use a different number of concurrent requests to reduce the performance impact of state sync.
 */


data class ExternalStorageConfig (

    /* Location of state parts. */
    @Json(name = "location")
    val location: ExternalStorageLocation,

    /* The number of attempts the node will make to obtain a part from peers in the network before it fetches from external storage. */
    @Json(name = "external_storage_fallback_threshold")
    val externalStorageFallbackThreshold: kotlin.Int? = 3,

    /* When fetching state parts from external storage, throttle fetch requests to this many concurrent requests. */
    @Json(name = "num_concurrent_requests")
    val numConcurrentRequests: kotlin.Int? = 25,

    /* During catchup, the node will use a different number of concurrent requests to reduce the performance impact of state sync. */
    @Json(name = "num_concurrent_requests_during_catchup")
    val numConcurrentRequestsDuringCatchup: kotlin.Int? = 5

) {


}

