/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ExternalStorageLocationOneOf
import org.openapitools.client.models.ExternalStorageLocationOneOf1
import org.openapitools.client.models.ExternalStorageLocationOneOf1Filesystem
import org.openapitools.client.models.ExternalStorageLocationOneOf2
import org.openapitools.client.models.ExternalStorageLocationOneOf2GCS
import org.openapitools.client.models.ExternalStorageLocationOneOfS3

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param S3 
 * @param filesystem 
 * @param GCS 
 */


data class ExternalStorageLocation (

    @Json(name = "S3")
    val S3: ExternalStorageLocationOneOfS3,

    @Json(name = "Filesystem")
    val filesystem: ExternalStorageLocationOneOf1Filesystem,

    @Json(name = "GCS")
    val GCS: ExternalStorageLocationOneOf2GCS

) {


}

