/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The execution has succeeded and returned some value or an empty vec encoded in base64.
 *
 * @param successValue 
 */


data class FinalExecutionStatusOneOf1 (

    @Json(name = "SuccessValue")
    val successValue: kotlin.String

) {


}

