/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TxExecutionError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The execution has failed with the given error.
 *
 * @param failure 
 */


data class FinalExecutionStatusOneOf (

    @Json(name = "Failure")
    val failure: TxExecutionError

) {


}

