/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WasmTrap

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A trap happened during execution of a binary  Note: this is only to deserialize old data, use execution error for new data
 *
 * @param wasmTrap 
 */


data class FunctionCallErrorOneOf3 (

    @Json(name = "WasmTrap")
    val wasmTrap: WasmTrap

) {


}

