/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CompilationError
import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError
import org.openapitools.client.models.FunctionCallErrorOneOf
import org.openapitools.client.models.FunctionCallErrorOneOf1
import org.openapitools.client.models.FunctionCallErrorOneOf2
import org.openapitools.client.models.FunctionCallErrorOneOf3
import org.openapitools.client.models.FunctionCallErrorOneOf4
import org.openapitools.client.models.FunctionCallErrorOneOf5
import org.openapitools.client.models.HostError
import org.openapitools.client.models.MethodResolveError
import org.openapitools.client.models.WasmTrap

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializable version of `near-vm-runner::FunctionCallError`.  Must never reorder/remove elements, can only add new variants at the end (but do that very carefully). It describes stable serialization format, and only used by serialization logic.
 *
 * @param compilationError 
 * @param linkError 
 * @param methodResolveError 
 * @param wasmTrap 
 * @param hostError 
 * @param executionError 
 */


data class FunctionCallError (

    @Json(name = "CompilationError")
    val compilationError: CompilationError,

    @Json(name = "LinkError")
    val linkError: CompilationErrorOneOf2WasmerCompileError,

    @Json(name = "MethodResolveError")
    val methodResolveError: MethodResolveError,

    @Json(name = "WasmTrap")
    val wasmTrap: WasmTrap,

    @Json(name = "HostError")
    val hostError: HostError,

    @Json(name = "ExecutionError")
    val executionError: kotlin.String

) {


}

