/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.HostError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Note: this is only to deserialize old data, use execution error for new data
 *
 * @param hostError 
 */


data class FunctionCallErrorOneOf4 (

    @Json(name = "HostError")
    val hostError: HostError

) {


}

