/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccessKeyPermissionView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param balance 
 * @param numNonces 
 * @param permission 
 */


data class GasKeyView (

    @Json(name = "balance")
    val balance: kotlin.Int,

    @Json(name = "num_nonces")
    val numNonces: kotlin.Int,

    @Json(name = "permission")
    val permission: AccessKeyPermissionView

) {


}

