/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.HostErrorOneOf7ProhibitedInView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The host function was deprecated.
 *
 * @param deprecated 
 */


data class HostErrorOneOf16 (

    @Json(name = "Deprecated")
    val deprecated: HostErrorOneOf7ProhibitedInView

) {


}

