/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf5ContractSizeExceeded
import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError
import org.openapitools.client.models.HostErrorOneOf
import org.openapitools.client.models.HostErrorOneOf1
import org.openapitools.client.models.HostErrorOneOf10
import org.openapitools.client.models.HostErrorOneOf11
import org.openapitools.client.models.HostErrorOneOf12
import org.openapitools.client.models.HostErrorOneOf12NumberPromisesExceeded
import org.openapitools.client.models.HostErrorOneOf13
import org.openapitools.client.models.HostErrorOneOf13NumberInputDataDependenciesExceeded
import org.openapitools.client.models.HostErrorOneOf14
import org.openapitools.client.models.HostErrorOneOf15
import org.openapitools.client.models.HostErrorOneOf16
import org.openapitools.client.models.HostErrorOneOf17
import org.openapitools.client.models.HostErrorOneOf18
import org.openapitools.client.models.HostErrorOneOf19
import org.openapitools.client.models.HostErrorOneOf1InvalidPromiseIndex
import org.openapitools.client.models.HostErrorOneOf2
import org.openapitools.client.models.HostErrorOneOf2InvalidPromiseResultIndex
import org.openapitools.client.models.HostErrorOneOf3
import org.openapitools.client.models.HostErrorOneOf3InvalidRegisterId
import org.openapitools.client.models.HostErrorOneOf4
import org.openapitools.client.models.HostErrorOneOf4IteratorWasInvalidated
import org.openapitools.client.models.HostErrorOneOf5
import org.openapitools.client.models.HostErrorOneOf5InvalidReceiptIndex
import org.openapitools.client.models.HostErrorOneOf6
import org.openapitools.client.models.HostErrorOneOf7
import org.openapitools.client.models.HostErrorOneOf7ProhibitedInView
import org.openapitools.client.models.HostErrorOneOf8
import org.openapitools.client.models.HostErrorOneOf8NumberOfLogsExceeded
import org.openapitools.client.models.HostErrorOneOf9
import org.openapitools.client.models.HostErrorOneOfGuestPanic

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param guestPanic 
 * @param invalidPromiseIndex 
 * @param invalidPromiseResultIndex 
 * @param invalidRegisterId 
 * @param iteratorWasInvalidated 
 * @param invalidReceiptIndex 
 * @param invalidIteratorIndex 
 * @param prohibitedInView 
 * @param numberOfLogsExceeded 
 * @param keyLengthExceeded 
 * @param valueLengthExceeded 
 * @param totalLogLengthExceeded 
 * @param numberPromisesExceeded 
 * @param numberInputDataDependenciesExceeded 
 * @param returnedValueLengthExceeded 
 * @param contractSizeExceeded 
 * @param deprecated 
 * @param ecRecoverError 
 * @param altBn128InvalidInput 
 * @param ed25519VerifyInvalidInput 
 */


data class HostError (

    @Json(name = "GuestPanic")
    val guestPanic: HostErrorOneOfGuestPanic,

    @Json(name = "InvalidPromiseIndex")
    val invalidPromiseIndex: HostErrorOneOf1InvalidPromiseIndex,

    @Json(name = "InvalidPromiseResultIndex")
    val invalidPromiseResultIndex: HostErrorOneOf2InvalidPromiseResultIndex,

    @Json(name = "InvalidRegisterId")
    val invalidRegisterId: HostErrorOneOf3InvalidRegisterId,

    @Json(name = "IteratorWasInvalidated")
    val iteratorWasInvalidated: HostErrorOneOf4IteratorWasInvalidated,

    @Json(name = "InvalidReceiptIndex")
    val invalidReceiptIndex: HostErrorOneOf5InvalidReceiptIndex,

    @Json(name = "InvalidIteratorIndex")
    val invalidIteratorIndex: HostErrorOneOf4IteratorWasInvalidated,

    @Json(name = "ProhibitedInView")
    val prohibitedInView: HostErrorOneOf7ProhibitedInView,

    @Json(name = "NumberOfLogsExceeded")
    val numberOfLogsExceeded: HostErrorOneOf8NumberOfLogsExceeded,

    @Json(name = "KeyLengthExceeded")
    val keyLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded,

    @Json(name = "ValueLengthExceeded")
    val valueLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded,

    @Json(name = "TotalLogLengthExceeded")
    val totalLogLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded,

    @Json(name = "NumberPromisesExceeded")
    val numberPromisesExceeded: HostErrorOneOf12NumberPromisesExceeded,

    @Json(name = "NumberInputDataDependenciesExceeded")
    val numberInputDataDependenciesExceeded: HostErrorOneOf13NumberInputDataDependenciesExceeded,

    @Json(name = "ReturnedValueLengthExceeded")
    val returnedValueLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded,

    @Json(name = "ContractSizeExceeded")
    val contractSizeExceeded: ActionsValidationErrorOneOf5ContractSizeExceeded,

    @Json(name = "Deprecated")
    val deprecated: HostErrorOneOf7ProhibitedInView,

    @Json(name = "ECRecoverError")
    val ecRecoverError: CompilationErrorOneOf2WasmerCompileError,

    @Json(name = "AltBn128InvalidInput")
    val altBn128InvalidInput: CompilationErrorOneOf2WasmerCompileError,

    @Json(name = "Ed25519VerifyInvalidInput")
    val ed25519VerifyInvalidInput: CompilationErrorOneOf2WasmerCompileError

) {


}

