/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Invalid input to alt_bn128 family of functions (e.g., point which isn't on the curve).
 *
 * @param altBn128InvalidInput 
 */


data class HostErrorOneOf18 (

    @Json(name = "AltBn128InvalidInput")
    val altBn128InvalidInput: CompilationErrorOneOf2WasmerCompileError

) {


}

