/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionsValidationErrorOneOf5ContractSizeExceeded

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The contract size for DeployContract action exceeded the limit.
 *
 * @param contractSizeExceeded 
 */


data class HostErrorOneOf15 (

    @Json(name = "ContractSizeExceeded")
    val contractSizeExceeded: ActionsValidationErrorOneOf5ContractSizeExceeded

) {


}

