/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * General errors for ECDSA recover.
 *
 * @param ecRecoverError 
 */


data class HostErrorOneOf17 (

    @Json(name = "ECRecoverError")
    val ecRecoverError: CompilationErrorOneOf2WasmerCompileError

) {


}

