/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.HostErrorOneOf8NumberOfLogsExceeded

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The total number of logs will exceed the limit.
 *
 * @param numberOfLogsExceeded 
 */


data class HostErrorOneOf8 (

    @Json(name = "NumberOfLogsExceeded")
    val numberOfLogsExceeded: HostErrorOneOf8NumberOfLogsExceeded

) {


}

