/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The returned value length exceeded the limit.
 *
 * @param returnedValueLengthExceeded 
 */


data class HostErrorOneOf14 (

    @Json(name = "ReturnedValueLengthExceeded")
    val returnedValueLengthExceeded: ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded

) {


}

