/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param limit 
 * @param numberOfInputDataDependencies 
 */


data class HostErrorOneOf13NumberInputDataDependenciesExceeded (

    @Json(name = "limit")
    val limit: kotlin.Int,

    @Json(name = "number_of_input_data_dependencies")
    val numberOfInputDataDependencies: kotlin.Int

) {


}

