/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.HostErrorOneOf4IteratorWasInvalidated

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Iterator index `iterator_index` does not exist
 *
 * @param invalidIteratorIndex 
 */


data class HostErrorOneOf6 (

    @Json(name = "InvalidIteratorIndex")
    val invalidIteratorIndex: HostErrorOneOf4IteratorWasInvalidated

) {


}

