/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InvalidTxErrorOneOf4NonceTooLarge

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Transaction nonce is larger than the upper bound given by the block height
 *
 * @param nonceTooLarge 
 */


data class InvalidTxErrorOneOf4 (

    @Json(name = "NonceTooLarge")
    val nonceTooLarge: InvalidTxErrorOneOf4NonceTooLarge

) {


}

