/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionErrorKindOneOf5DeleteKeyDoesNotExist
import org.openapitools.client.models.HostErrorOneOf7ProhibitedInView
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf1
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf1ReceiverMismatch
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf2
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf3
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf3NotEnoughAllowance

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessKeyNotFound 
 * @param receiverMismatch 
 * @param methodNameMismatch 
 * @param notEnoughAllowance 
 */


data class InvalidAccessKeyError (

    @Json(name = "AccessKeyNotFound")
    val accessKeyNotFound: ActionErrorKindOneOf5DeleteKeyDoesNotExist,

    @Json(name = "ReceiverMismatch")
    val receiverMismatch: InvalidAccessKeyErrorOneOf1ReceiverMismatch,

    @Json(name = "MethodNameMismatch")
    val methodNameMismatch: HostErrorOneOf7ProhibitedInView,

    @Json(name = "NotEnoughAllowance")
    val notEnoughAllowance: InvalidAccessKeyErrorOneOf3NotEnoughAllowance

) {


}

