/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param congestionLevel A value between 0 (no congestion) and 1 (max congestion).
 * @param shardId The congested shard.
 */


data class InvalidTxErrorOneOf11ShardCongested (

    /* A value between 0 (no congestion) and 1 (max congestion). */
    @Json(name = "congestion_level")
    val congestionLevel: kotlin.Double,

    /* The congested shard. */
    @Json(name = "shard_id")
    val shardId: kotlin.Int

) {


}

