/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InvalidTxErrorOneOf12ShardStuck

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The receiver shard of the transaction missed several chunks and rejects new transaction until it can make progress again.
 *
 * @param shardStuck 
 */


data class InvalidTxErrorOneOf12 (

    @Json(name = "ShardStuck")
    val shardStuck: InvalidTxErrorOneOf12ShardStuck

) {


}

