/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionsValidationError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An error occurred while validating actions of a Transaction.
 *
 * @param actionsValidation 
 */


data class InvalidTxErrorOneOf8 (

    @Json(name = "ActionsValidation")
    val actionsValidation: ActionsValidationError

) {


}

