/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param akNonce 
 * @param txNonce 
 */


data class InvalidTxErrorOneOf3InvalidNonce (

    @Json(name = "ak_nonce")
    val akNonce: kotlin.Int,

    @Json(name = "tx_nonce")
    val txNonce: kotlin.Int

) {


}

