/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InvalidTxErrorOneOf7LackBalanceForState

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Signer account doesn't have enough balance after transaction.
 *
 * @param lackBalanceForState 
 */


data class InvalidTxErrorOneOf7 (

    @Json(name = "LackBalanceForState")
    val lackBalanceForState: InvalidTxErrorOneOf7LackBalanceForState

) {


}

