/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.HostErrorOneOf7ProhibitedInView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Transaction method name isn't allowed by the access key
 *
 * @param methodNameMismatch 
 */


data class InvalidAccessKeyErrorOneOf2 (

    @Json(name = "MethodNameMismatch")
    val methodNameMismatch: HostErrorOneOf7ProhibitedInView

) {


}

