/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount Required balance to cover the state.
 * @param signerId An account which doesn't have enough balance to cover storage.
 */


data class InvalidTxErrorOneOf7LackBalanceForState (

    /* Required balance to cover the state. */
    @Json(name = "amount")
    val amount: kotlin.String,

    /* An account which doesn't have enough balance to cover storage. */
    @Json(name = "signer_id")
    val signerId: kotlin.String

) {


}

