/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InvalidAccessKeyError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Happens if a wrong AccessKey used or AccessKey has not enough permissions
 *
 * @param invalidAccessKeyError 
 */


data class InvalidTxErrorOneOf (

    @Json(name = "InvalidAccessKeyError")
    val invalidAccessKeyError: InvalidAccessKeyError

) {


}

