/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InvalidTxErrorOneOf3InvalidNonce

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Transaction nonce must be strictly greater than `account[access_key].nonce`.
 *
 * @param invalidNonce 
 */


data class InvalidTxErrorOneOf3 (

    @Json(name = "InvalidNonce")
    val invalidNonce: InvalidTxErrorOneOf3InvalidNonce

) {


}

