/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InvalidTxErrorOneOf1InvalidSignerId

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * TX signer_id is not a valid [`AccountId`]
 *
 * @param invalidSignerId 
 */


data class InvalidTxErrorOneOf1 (

    @Json(name = "InvalidSignerId")
    val invalidSignerId: InvalidTxErrorOneOf1InvalidSignerId

) {


}

