/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InvalidAccessKeyErrorOneOf1ReceiverMismatch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Transaction `receiver_id` doesn't match the access key receiver_id
 *
 * @param receiverMismatch 
 */


data class InvalidAccessKeyErrorOneOf1 (

    @Json(name = "ReceiverMismatch")
    val receiverMismatch: InvalidAccessKeyErrorOneOf1ReceiverMismatch

) {


}

