/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RpcValidatorsOrderedRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param jsonrpc 
 * @param method 
 * @param params 
 */


data class JsonRpcRequestForEXPERIMENTALValidatorsOrdered (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "jsonrpc")
    val jsonrpc: kotlin.String,

    @Json(name = "method")
    val method: JsonRpcRequestForEXPERIMENTALValidatorsOrdered.Method,

    @Json(name = "params")
    val params: RpcValidatorsOrderedRequest

) {

    /**
     * 
     *
     * Values: EXPERIMENTAL_validators_ordered
     */
    @JsonClass(generateAdapter = false)
    enum class Method(val value: kotlin.String) {
        @Json(name = "EXPERIMENTAL_validators_ordered") EXPERIMENTAL_validators_ordered("EXPERIMENTAL_validators_ordered");
    }

}

