/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.JsonRpcResponseForArrayOfRangeOfUint64AndRpcErrorOneOf1
import org.openapitools.client.models.JsonRpcResponseForRpcChunkResponseAndRpcErrorOneOf
import org.openapitools.client.models.RpcChunkResponse
import org.openapitools.client.models.RpcError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param result 
 * @param error 
 */


data class JsonRpcResponseForRpcChunkResponseAndRpcError (

    @Json(name = "result")
    val result: RpcChunkResponse,

    @Json(name = "error")
    val error: RpcError

) {


}

