/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MissingTrieValueContext

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param context 
 * @param hash 
 */


data class MissingTrieValue (

    @Json(name = "context")
    val context: MissingTrieValueContext,

    @Json(name = "hash")
    val hash: kotlin.String

) {


}

