/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ReceiptEnumViewOneOf
import org.openapitools.client.models.ReceiptEnumViewOneOf1
import org.openapitools.client.models.ReceiptEnumViewOneOf1Data
import org.openapitools.client.models.ReceiptEnumViewOneOf2
import org.openapitools.client.models.ReceiptEnumViewOneOf2GlobalContractDistribution
import org.openapitools.client.models.ReceiptEnumViewOneOfAction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param action 
 * @param `data` 
 * @param globalContractDistribution 
 */


data class ReceiptEnumView (

    @Json(name = "Action")
    val action: ReceiptEnumViewOneOfAction,

    @Json(name = "Data")
    val `data`: ReceiptEnumViewOneOf1Data,

    @Json(name = "GlobalContractDistribution")
    val globalContractDistribution: ReceiptEnumViewOneOf2GlobalContractDistribution

) {


}

