/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionsValidationErrorOneOf4InvalidAccountId

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The `signer_id` of an ActionReceipt is not valid.
 *
 * @param invalidSignerId 
 */


data class ReceiptValidationErrorOneOf2 (

    @Json(name = "InvalidSignerId")
    val invalidSignerId: ActionsValidationErrorOneOf4InvalidAccountId

) {


}

