/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BlockHeaderView
import org.openapitools.client.models.ChunkHeaderView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param author The AccountId of the author of the Block
 * @param chunks 
 * @param header 
 */


data class RpcBlockResponse (

    /* The AccountId of the author of the Block */
    @Json(name = "author")
    val author: kotlin.String,

    @Json(name = "chunks")
    val chunks: kotlin.collections.List<ChunkHeaderView>,

    @Json(name = "header")
    val header: BlockHeaderView

) {


}

