/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cause 
 * @param name 
 */


data class RpcErrorOneOf1 (

    @Json(name = "cause")
    val cause: kotlin.Any?,

    @Json(name = "name")
    val name: RpcErrorOneOf1.Name

) {

    /**
     * 
     *
     * Values: HANDLER_ERROR
     */
    @JsonClass(generateAdapter = false)
    enum class Name(val value: kotlin.String) {
        @Json(name = "HANDLER_ERROR") HANDLER_ERROR("HANDLER_ERROR");
    }

}

