/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LightClientBlockLiteView
import org.openapitools.client.models.MerklePathItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockHeaderLite 
 * @param blockProof 
 */


data class RpcLightClientBlockProofResponse (

    @Json(name = "block_header_lite")
    val blockHeaderLite: LightClientBlockLiteView,

    @Json(name = "block_proof")
    val blockProof: kotlin.collections.List<MerklePathItem>

) {


}

