/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BlockHeaderInnerLiteView
import org.openapitools.client.models.BlockHeaderViewApprovalsInner
import org.openapitools.client.models.ValidatorStakeView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A state for the current head of a light client. More info [here](https://nomicon.io/ChainSpec/LightClient).
 *
 * @param approvalsAfterNext 
 * @param innerLite Inner part of the block header that gets hashed, split into two parts, one that is sent    to light clients, and the rest
 * @param innerRestHash 
 * @param nextBlockInnerHash 
 * @param nextBps 
 * @param prevBlockHash 
 */


data class RpcLightClientNextBlockResponse (

    @Json(name = "approvals_after_next")
    val approvalsAfterNext: kotlin.collections.List<BlockHeaderViewApprovalsInner>? = null,

    /* Inner part of the block header that gets hashed, split into two parts, one that is sent    to light clients, and the rest */
    @Json(name = "inner_lite")
    val innerLite: BlockHeaderInnerLiteView? = null,

    @Json(name = "inner_rest_hash")
    val innerRestHash: kotlin.String? = null,

    @Json(name = "next_block_inner_hash")
    val nextBlockInnerHash: kotlin.String? = null,

    @Json(name = "next_bps")
    val nextBps: kotlin.collections.List<ValidatorStakeView>? = null,

    @Json(name = "prev_block_hash")
    val prevBlockHash: kotlin.String? = null

) {


}

