/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockHash 
 * @param lightClientHead 
 */


data class RpcLightClientBlockProofRequest (

    @Json(name = "block_hash")
    val blockHash: kotlin.String,

    @Json(name = "light_client_head")
    val lightClientHead: kotlin.String

) {


}

