/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TxExecutionStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param signedTxBase64 
 * @param waitUntil 
 */


data class RpcSendTransactionRequest (

    @Json(name = "signed_tx_base64")
    val signedTxBase64: kotlin.ByteArray,

    @Json(name = "wait_until")
    val waitUntil: TxExecutionStatus? = null

) {


}

