/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StateChangeWithCauseView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockHash 
 * @param changes 
 */


data class RpcStateChangesInBlockResponse (

    @Json(name = "block_hash")
    val blockHash: kotlin.String,

    @Json(name = "changes")
    val changes: kotlin.collections.List<StateChangeWithCauseView>

) {


}

