/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CurrentEpochValidatorInfo
import org.openapitools.client.models.NextEpochValidatorInfo
import org.openapitools.client.models.ValidatorKickoutView
import org.openapitools.client.models.ValidatorStakeView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information about this epoch validators and next epoch validators
 *
 * @param currentFishermen Fishermen for the current epoch
 * @param currentProposals Proposals in the current epoch
 * @param currentValidators Validators for the current epoch
 * @param epochHeight Epoch height
 * @param epochStartHeight Epoch start block height
 * @param nextFishermen Fishermen for the next epoch
 * @param nextValidators Validators for the next epoch
 * @param prevEpochKickout Kickout in the previous epoch
 */


data class RpcValidatorResponse (

    /* Fishermen for the current epoch */
    @Json(name = "current_fishermen")
    val currentFishermen: kotlin.collections.List<ValidatorStakeView>,

    /* Proposals in the current epoch */
    @Json(name = "current_proposals")
    val currentProposals: kotlin.collections.List<ValidatorStakeView>,

    /* Validators for the current epoch */
    @Json(name = "current_validators")
    val currentValidators: kotlin.collections.List<CurrentEpochValidatorInfo>,

    /* Epoch height */
    @Json(name = "epoch_height")
    val epochHeight: kotlin.Int,

    /* Epoch start block height */
    @Json(name = "epoch_start_height")
    val epochStartHeight: kotlin.Int,

    /* Fishermen for the next epoch */
    @Json(name = "next_fishermen")
    val nextFishermen: kotlin.collections.List<ValidatorStakeView>,

    /* Validators for the next epoch */
    @Json(name = "next_validators")
    val nextValidators: kotlin.collections.List<NextEpochValidatorInfo>,

    /* Kickout in the previous epoch */
    @Json(name = "prev_epoch_kickout")
    val prevEpochKickout: kotlin.collections.List<ValidatorKickoutView>

) {


}

