/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Counterpart to `ShardLayoutV2` composed of maps with string keys to aid serde serialization.
 *
 * @param boundaryAccounts 
 * @param idToIndexMap 
 * @param indexToIdMap 
 * @param shardIds 
 * @param version 
 * @param shardsParentMap 
 * @param shardsSplitMap 
 */


data class ShardLayoutV2 (

    @Json(name = "boundary_accounts")
    val boundaryAccounts: kotlin.collections.List<kotlin.String>,

    @Json(name = "id_to_index_map")
    val idToIndexMap: kotlin.collections.Map<kotlin.String, kotlin.Int>,

    @Json(name = "index_to_id_map")
    val indexToIdMap: kotlin.collections.Map<kotlin.String, kotlin.Int>,

    @Json(name = "shard_ids")
    val shardIds: kotlin.collections.List<kotlin.Int>,

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "shards_parent_map")
    val shardsParentMap: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @Json(name = "shards_split_map")
    val shardsSplitMap: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.Int>>? = null

) {


}

