/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * `ShardUId` is a unique representation for shards from different shard layouts.  Comparing to `ShardId`, which is just an ordinal number ranging from 0 to NUM_SHARDS-1, `ShardUId` provides a way to unique identify shards when shard layouts may change across epochs. This is important because we store states indexed by shards in our database, so we need a way to unique identify shard even when shards change across epochs. Another difference between `ShardUId` and `ShardId` is that `ShardUId` should only exist in a node's internal state while `ShardId` can be exposed to outside APIs and used in protocol level information (for example, `ShardChunkHeader` contains `ShardId` instead of `ShardUId`)
 *
 * @param shardId 
 * @param version 
 */


data class ShardUId (

    @Json(name = "shard_id")
    val shardId: kotlin.Int,

    @Json(name = "version")
    val version: kotlin.Int

) {


}

