/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountWithPublicKey
import org.openapitools.client.models.SyncCheckpoint

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param syncCheckpoint 
 * @param changesType 
 * @param propertyKeys 
 */


data class SingleAccessKeyChangesBySyncCheckpoint (

    @Json(name = "sync_checkpoint")
    val syncCheckpoint: SyncCheckpoint,

    @Json(name = "changes_type")
    val changesType: SingleAccessKeyChangesBySyncCheckpoint.ChangesType,

    @Json(name = "keys")
    val propertyKeys: kotlin.collections.List<AccountWithPublicKey>

) {

    /**
     * 
     *
     * Values: single_access_key_changes
     */
    @JsonClass(generateAdapter = false)
    enum class ChangesType(val value: kotlin.String) {
        @Json(name = "single_access_key_changes") single_access_key_changes("single_access_key_changes");
    }

}

