/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StateChangeWithCauseViewOneOf4Change

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param change 
 * @param type 
 */


data class StateChangeWithCauseViewOneOf4 (

    @Json(name = "change")
    val change: StateChangeWithCauseViewOneOf4Change,

    @Json(name = "type")
    val type: StateChangeWithCauseViewOneOf4.Type

) {

    /**
     * 
     *
     * Values: gas_key_update
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "gas_key_update") gas_key_update("gas_key_update");
    }

}

