/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StateChangeWithCauseViewOneOf9Change

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param change 
 * @param type 
 */


data class StateChangeWithCauseViewOneOf9 (

    @Json(name = "change")
    val change: StateChangeWithCauseViewOneOf9Change,

    @Json(name = "type")
    val type: StateChangeWithCauseViewOneOf9.Type

) {

    /**
     * 
     *
     * Values: contract_code_update
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "contract_code_update") contract_code_update("contract_code_update");
    }

}

