/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param change 
 * @param type 
 */


data class StateChangeWithCauseViewOneOf1 (

    @Json(name = "change")
    val change: ActionErrorKindOneOfAccountAlreadyExists,

    @Json(name = "type")
    val type: StateChangeWithCauseViewOneOf1.Type

) {

    /**
     * 
     *
     * Values: account_deletion
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "account_deletion") account_deletion("account_deletion");
    }

}

