/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StateChangeWithCauseViewOneOfChange

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param change 
 * @param type 
 */


data class StateChangeWithCauseViewOneOf (

    @Json(name = "change")
    val change: StateChangeWithCauseViewOneOfChange,

    @Json(name = "type")
    val type: StateChangeWithCauseViewOneOf.Type

) {

    /**
     * 
     *
     * Values: account_update
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "account_update") account_update("account_update");
    }

}

