/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * In-memory trie could not be loaded for some reason.
 *
 * @param memTrieLoadingError 
 */


data class StorageErrorOneOf3 (

    @Json(name = "MemTrieLoadingError")
    val memTrieLoadingError: kotlin.String

) {


}

