/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MissingTrieValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Requested trie value by its hash which is missing in storage.
 *
 * @param missingTrieValue 
 */


data class StorageErrorOneOf (

    @Json(name = "MissingTrieValue")
    val missingTrieValue: MissingTrieValue

) {


}

