/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ExternalStorageConfig
import org.openapitools.client.models.SyncConfigOneOf

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Configures how to fetch state parts during state sync.
 *
 * @param externalStorage 
 */


data class SyncConfig (

    @Json(name = "ExternalStorage")
    val externalStorage: ExternalStorageConfig

) {


}

