/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An error happened during Action execution
 *
 * @param actionError 
 */


data class TxExecutionErrorOneOf (

    @Json(name = "ActionError")
    val actionError: ActionError

) {


}

