/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ValidatorKickoutReasonOneOf2NotEnoughStake

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Validator stake is now below threshold
 *
 * @param notEnoughStake 
 */


data class ValidatorKickoutReasonOneOf2 (

    @Json(name = "NotEnoughStake")
    val notEnoughStake: ValidatorKickoutReasonOneOf2NotEnoughStake

) {


}

