/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ValidatorKickoutReasonOneOfNotEnoughBlocks

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Validator didn't produce enough chunk endorsements.
 *
 * @param notEnoughChunkEndorsements 
 */


data class ValidatorKickoutReasonOneOf3 (

    @Json(name = "NotEnoughChunkEndorsements")
    val notEnoughChunkEndorsements: ValidatorKickoutReasonOneOfNotEnoughBlocks

) {


}

