/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ValidatorKickoutReasonOneOf
import org.openapitools.client.models.ValidatorKickoutReasonOneOf1
import org.openapitools.client.models.ValidatorKickoutReasonOneOf2
import org.openapitools.client.models.ValidatorKickoutReasonOneOf2NotEnoughStake
import org.openapitools.client.models.ValidatorKickoutReasonOneOf3
import org.openapitools.client.models.ValidatorKickoutReasonOneOf4
import org.openapitools.client.models.ValidatorKickoutReasonOneOf4ProtocolVersionTooOld
import org.openapitools.client.models.ValidatorKickoutReasonOneOfNotEnoughBlocks

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Reasons for removing a validator from the validator set.
 *
 * @param notEnoughBlocks 
 * @param notEnoughChunks 
 * @param notEnoughStake 
 * @param notEnoughChunkEndorsements 
 * @param protocolVersionTooOld 
 */


data class ValidatorKickoutReason (

    @Json(name = "NotEnoughBlocks")
    val notEnoughBlocks: ValidatorKickoutReasonOneOfNotEnoughBlocks,

    @Json(name = "NotEnoughChunks")
    val notEnoughChunks: ValidatorKickoutReasonOneOfNotEnoughBlocks,

    @Json(name = "NotEnoughStake")
    val notEnoughStake: ValidatorKickoutReasonOneOf2NotEnoughStake,

    @Json(name = "NotEnoughChunkEndorsements")
    val notEnoughChunkEndorsements: ValidatorKickoutReasonOneOfNotEnoughBlocks,

    @Json(name = "ProtocolVersionTooOld")
    val protocolVersionTooOld: ValidatorKickoutReasonOneOf4ProtocolVersionTooOld

) {


}

