/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param stakeU128 
 * @param thresholdU128 
 */


data class ValidatorKickoutReasonOneOf2NotEnoughStake (

    @Json(name = "stake_u128")
    val stakeU128: kotlin.String,

    @Json(name = "threshold_u128")
    val thresholdU128: kotlin.String

) {


}

