/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Data structure for semver version and github tag or commit.
 *
 * @param build 
 * @param commit 
 * @param version 
 * @param rustcVersion 
 */


data class Version (

    @Json(name = "build")
    val build: kotlin.String,

    @Json(name = "commit")
    val commit: kotlin.String,

    @Json(name = "version")
    val version: kotlin.String,

    @Json(name = "rustc_version")
    val rustcVersion: kotlin.String? = ""

) {


}

