/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SyncCheckpoint

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param syncCheckpoint 
 * @param codeHash 
 * @param requestType 
 */


data class ViewGlobalContractCodeBySyncCheckpoint (

    @Json(name = "sync_checkpoint")
    val syncCheckpoint: SyncCheckpoint,

    @Json(name = "code_hash")
    val codeHash: kotlin.String,

    @Json(name = "request_type")
    val requestType: ViewGlobalContractCodeBySyncCheckpoint.RequestType

) {

    /**
     * 
     *
     * Values: view_global_contract_code
     */
    @JsonClass(generateAdapter = false)
    enum class RequestType(val value: kotlin.String) {
        @Json(name = "view_global_contract_code") view_global_contract_code("view_global_contract_code");
    }

}

