/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Configuration specific to ChunkStateWitness.
 *
 * @param combinedTransactionsSizeLimit Maximum size of transactions contained inside ChunkStateWitness.  A witness contains transactions from both the previous chunk and the current one. This parameter limits the sum of sizes of transactions from both of those chunks.
 * @param mainStorageProofSizeSoftLimit Size limit for storage proof generated while executing receipts in a chunk. After this limit is reached we defer execution of any new receipts.
 * @param newTransactionsValidationStateSizeSoftLimit Soft size limit of storage proof used to validate new transactions in ChunkStateWitness.
 */


data class WitnessConfigView (

    /* Maximum size of transactions contained inside ChunkStateWitness.  A witness contains transactions from both the previous chunk and the current one. This parameter limits the sum of sizes of transactions from both of those chunks. */
    @Json(name = "combined_transactions_size_limit")
    val combinedTransactionsSizeLimit: kotlin.Int,

    /* Size limit for storage proof generated while executing receipts in a chunk. After this limit is reached we defer execution of any new receipts. */
    @Json(name = "main_storage_proof_size_soft_limit")
    val mainStorageProofSizeSoftLimit: kotlin.Int,

    /* Soft size limit of storage proof used to validate new transactions in ChunkStateWitness. */
    @Json(name = "new_transactions_validation_state_size_soft_limit")
    val newTransactionsValidationStateSizeSoftLimit: kotlin.Int

) {


}

