/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AccessKeyCreationConfigView
import org.openapitools.client.models.Fee

class AccessKeyCreationConfigViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccessKeyCreationConfigView
        //val modelInstance = AccessKeyCreationConfigView()

        // to test the property `fullAccessCost` - Base cost of creating a full access access-key.
        should("test fullAccessCost") {
            // uncomment below to test the property
            //modelInstance.fullAccessCost shouldBe ("TODO")
        }

        // to test the property `functionCallCost` - Base cost of creating an access-key restricted to specific functions.
        should("test functionCallCost") {
            // uncomment below to test the property
            //modelInstance.functionCallCost shouldBe ("TODO")
        }

        // to test the property `functionCallCostPerByte` - Cost per byte of method_names of creating a restricted access-key.
        should("test functionCallCostPerByte") {
            // uncomment below to test the property
            //modelInstance.functionCallCostPerByte shouldBe ("TODO")
        }

    }
}
