/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AccessKeyPermissionViewOneOfFunctionCall

class AccessKeyPermissionViewOneOfFunctionCallTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccessKeyPermissionViewOneOfFunctionCall
        //val modelInstance = AccessKeyPermissionViewOneOfFunctionCall()

        // to test the property `methodNames`
        should("test methodNames") {
            // uncomment below to test the property
            //modelInstance.methodNames shouldBe ("TODO")
        }

        // to test the property `receiverId`
        should("test receiverId") {
            // uncomment below to test the property
            //modelInstance.receiverId shouldBe ("TODO")
        }

        // to test the property `allowance`
        should("test allowance") {
            // uncomment below to test the property
            //modelInstance.allowance shouldBe ("TODO")
        }

    }
}
