/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AccessKeyList
import org.openapitools.client.models.AccessKeyInfoView

class AccessKeyListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccessKeyList
        //val modelInstance = AccessKeyList()

        // to test the property `propertyKeys`
        should("test propertyKeys") {
            // uncomment below to test the property
            //modelInstance.propertyKeys shouldBe ("TODO")
        }

    }
}
