/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AccountChangesByFinality
import org.openapitools.client.models.Finality

class AccountChangesByFinalityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountChangesByFinality
        //val modelInstance = AccountChangesByFinality()

        // to test the property `finality`
        should("test finality") {
            // uncomment below to test the property
            //modelInstance.finality shouldBe ("TODO")
        }

        // to test the property `accountIds`
        should("test accountIds") {
            // uncomment below to test the property
            //modelInstance.accountIds shouldBe ("TODO")
        }

        // to test the property `changesType`
        should("test changesType") {
            // uncomment below to test the property
            //modelInstance.changesType shouldBe ("TODO")
        }

    }
}
