/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionViewOneOf3Stake

class ActionViewOneOf3StakeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionViewOneOf3Stake
        //val modelInstance = ActionViewOneOf3Stake()

        // to test the property `publicKey`
        should("test publicKey") {
            // uncomment below to test the property
            //modelInstance.publicKey shouldBe ("TODO")
        }

        // to test the property `stake`
        should("test stake") {
            // uncomment below to test the property
            //modelInstance.stake shouldBe ("TODO")
        }

    }
}
