/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionViewOneOf1
import org.openapitools.client.models.ActionViewOneOf1FunctionCall

class ActionViewOneOf1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionViewOneOf1
        //val modelInstance = ActionViewOneOf1()

        // to test the property `functionCall`
        should("test functionCall") {
            // uncomment below to test the property
            //modelInstance.functionCall shouldBe ("TODO")
        }

    }
}
