/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf20
import org.openapitools.client.models.ActionErrorKindOneOf20GlobalContractDoesNotExist

class ActionErrorKindOneOf20Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf20
        //val modelInstance = ActionErrorKindOneOf20()

        // to test the property `globalContractDoesNotExist`
        should("test globalContractDoesNotExist") {
            // uncomment below to test the property
            //modelInstance.globalContractDoesNotExist shouldBe ("TODO")
        }

    }
}
