/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf16DelegateActionSenderDoesNotMatchTxReceiver

class ActionErrorKindOneOf16DelegateActionSenderDoesNotMatchTxReceiverTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf16DelegateActionSenderDoesNotMatchTxReceiver
        //val modelInstance = ActionErrorKindOneOf16DelegateActionSenderDoesNotMatchTxReceiver()

        // to test the property `receiverId` - NEAR Account Identifier.  This is a unique, syntactically valid, human-readable account identifier on the NEAR network.  [See the crate-level docs for information about validation.](index.html#account-id-rules)  Also see [Error kind precedence](AccountId#error-kind-precedence).  ## Examples  ``` use near_account_id::AccountId;  let alice: AccountId = \"alice.near\".parse().unwrap();  assert!(\"ƒelicia.near\".parse::<AccountId>().is_err()); // (ƒ is not f) ```
        should("test receiverId") {
            // uncomment below to test the property
            //modelInstance.receiverId shouldBe ("TODO")
        }

        // to test the property `senderId` - NEAR Account Identifier.  This is a unique, syntactically valid, human-readable account identifier on the NEAR network.  [See the crate-level docs for information about validation.](index.html#account-id-rules)  Also see [Error kind precedence](AccountId#error-kind-precedence).  ## Examples  ``` use near_account_id::AccountId;  let alice: AccountId = \"alice.near\".parse().unwrap();  assert!(\"ƒelicia.near\".parse::<AccountId>().is_err()); // (ƒ is not f) ```
        should("test senderId") {
            // uncomment below to test the property
            //modelInstance.senderId shouldBe ("TODO")
        }

    }
}
