/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf4
import org.openapitools.client.models.ActionErrorKindOneOf4ActorNoPermission

class ActionErrorKindOneOf4Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf4
        //val modelInstance = ActionErrorKindOneOf4()

        // to test the property `actorNoPermission`
        should("test actorNoPermission") {
            // uncomment below to test the property
            //modelInstance.actorNoPermission shouldBe ("TODO")
        }

    }
}
