/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf9
import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists

class ActionErrorKindOneOf9Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf9
        //val modelInstance = ActionErrorKindOneOf9()

        // to test the property `triesToUnstake`
        should("test triesToUnstake") {
            // uncomment below to test the property
            //modelInstance.triesToUnstake shouldBe ("TODO")
        }

    }
}
