/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf17
import org.openapitools.client.models.InvalidAccessKeyError

class ActionErrorKindOneOf17Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf17
        //val modelInstance = ActionErrorKindOneOf17()

        // to test the property `delegateActionAccessKeyError`
        should("test delegateActionAccessKeyError") {
            // uncomment below to test the property
            //modelInstance.delegateActionAccessKeyError shouldBe ("TODO")
        }

    }
}
