/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf8
import org.openapitools.client.models.ActionErrorKindOneOf8LackBalanceForState

class ActionErrorKindOneOf8Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf8
        //val modelInstance = ActionErrorKindOneOf8()

        // to test the property `lackBalanceForState`
        should("test lackBalanceForState") {
            // uncomment below to test the property
            //modelInstance.lackBalanceForState shouldBe ("TODO")
        }

    }
}
