/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionViewOneOf2Transfer

class ActionViewOneOf2TransferTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionViewOneOf2Transfer
        //val modelInstance = ActionViewOneOf2Transfer()

        // to test the property `deposit`
        should("test deposit") {
            // uncomment below to test the property
            //modelInstance.deposit shouldBe ("TODO")
        }

    }
}
