/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf2
import org.openapitools.client.models.ActionErrorKindOneOf2CreateAccountOnlyByRegistrar

class ActionErrorKindOneOf2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf2
        //val modelInstance = ActionErrorKindOneOf2()

        // to test the property `createAccountOnlyByRegistrar`
        should("test createAccountOnlyByRegistrar") {
            // uncomment below to test the property
            //modelInstance.createAccountOnlyByRegistrar shouldBe ("TODO")
        }

    }
}
