/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf19DelegateActionNonceTooLarge

class ActionErrorKindOneOf19DelegateActionNonceTooLargeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf19DelegateActionNonceTooLarge
        //val modelInstance = ActionErrorKindOneOf19DelegateActionNonceTooLarge()

        // to test the property `delegateNonce`
        should("test delegateNonce") {
            // uncomment below to test the property
            //modelInstance.delegateNonce shouldBe ("TODO")
        }

        // to test the property `upperBound`
        should("test upperBound") {
            // uncomment below to test the property
            //modelInstance.upperBound shouldBe ("TODO")
        }

    }
}
