/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionViewOneOf10UseGlobalContract

class ActionViewOneOf10UseGlobalContractTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionViewOneOf10UseGlobalContract
        //val modelInstance = ActionViewOneOf10UseGlobalContract()

        // to test the property `codeHash`
        should("test codeHash") {
            // uncomment below to test the property
            //modelInstance.codeHash shouldBe ("TODO")
        }

    }
}
