/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf15
import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists

class ActionErrorKindOneOf15Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf15
        //val modelInstance = ActionErrorKindOneOf15()

        // to test the property `deleteAccountWithLargeState`
        should("test deleteAccountWithLargeState") {
            // uncomment below to test the property
            //modelInstance.deleteAccountWithLargeState shouldBe ("TODO")
        }

    }
}
