/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionsValidationErrorOneOf5ContractSizeExceeded

class ActionsValidationErrorOneOf5ContractSizeExceededTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionsValidationErrorOneOf5ContractSizeExceeded
        //val modelInstance = ActionsValidationErrorOneOf5ContractSizeExceeded()

        // to test the property `limit`
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `propertySize`
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

    }
}
