/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionViewOneOf9
import org.openapitools.client.models.ActionViewOneOfDeployContract

class ActionViewOneOf9Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionViewOneOf9
        //val modelInstance = ActionViewOneOf9()

        // to test the property `deployGlobalContractByAccountId`
        should("test deployGlobalContractByAccountId") {
            // uncomment below to test the property
            //modelInstance.deployGlobalContractByAccountId shouldBe ("TODO")
        }

    }
}
