/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionView
import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists
import org.openapitools.client.models.ActionViewOneOf
import org.openapitools.client.models.ActionViewOneOf1
import org.openapitools.client.models.ActionViewOneOf10
import org.openapitools.client.models.ActionViewOneOf10UseGlobalContract
import org.openapitools.client.models.ActionViewOneOf11
import org.openapitools.client.models.ActionViewOneOf1FunctionCall
import org.openapitools.client.models.ActionViewOneOf2
import org.openapitools.client.models.ActionViewOneOf2Transfer
import org.openapitools.client.models.ActionViewOneOf3
import org.openapitools.client.models.ActionViewOneOf3Stake
import org.openapitools.client.models.ActionViewOneOf4
import org.openapitools.client.models.ActionViewOneOf4AddKey
import org.openapitools.client.models.ActionViewOneOf5
import org.openapitools.client.models.ActionViewOneOf5DeleteKey
import org.openapitools.client.models.ActionViewOneOf6
import org.openapitools.client.models.ActionViewOneOf6DeleteAccount
import org.openapitools.client.models.ActionViewOneOf7
import org.openapitools.client.models.ActionViewOneOf7Delegate
import org.openapitools.client.models.ActionViewOneOf8
import org.openapitools.client.models.ActionViewOneOf9
import org.openapitools.client.models.ActionViewOneOfDeployContract

class ActionViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionView
        //val modelInstance = ActionView()

        // to test the property `deployContract`
        should("test deployContract") {
            // uncomment below to test the property
            //modelInstance.deployContract shouldBe ("TODO")
        }

        // to test the property `functionCall`
        should("test functionCall") {
            // uncomment below to test the property
            //modelInstance.functionCall shouldBe ("TODO")
        }

        // to test the property `transfer`
        should("test transfer") {
            // uncomment below to test the property
            //modelInstance.transfer shouldBe ("TODO")
        }

        // to test the property `stake`
        should("test stake") {
            // uncomment below to test the property
            //modelInstance.stake shouldBe ("TODO")
        }

        // to test the property `addKey`
        should("test addKey") {
            // uncomment below to test the property
            //modelInstance.addKey shouldBe ("TODO")
        }

        // to test the property `deleteKey`
        should("test deleteKey") {
            // uncomment below to test the property
            //modelInstance.deleteKey shouldBe ("TODO")
        }

        // to test the property `deleteAccount`
        should("test deleteAccount") {
            // uncomment below to test the property
            //modelInstance.deleteAccount shouldBe ("TODO")
        }

        // to test the property ``delegate``
        should("test `delegate`") {
            // uncomment below to test the property
            //modelInstance.`delegate` shouldBe ("TODO")
        }

        // to test the property `deployGlobalContract`
        should("test deployGlobalContract") {
            // uncomment below to test the property
            //modelInstance.deployGlobalContract shouldBe ("TODO")
        }

        // to test the property `deployGlobalContractByAccountId`
        should("test deployGlobalContractByAccountId") {
            // uncomment below to test the property
            //modelInstance.deployGlobalContractByAccountId shouldBe ("TODO")
        }

        // to test the property `useGlobalContract`
        should("test useGlobalContract") {
            // uncomment below to test the property
            //modelInstance.useGlobalContract shouldBe ("TODO")
        }

        // to test the property `useGlobalContractByAccountId`
        should("test useGlobalContractByAccountId") {
            // uncomment below to test the property
            //modelInstance.useGlobalContractByAccountId shouldBe ("TODO")
        }

    }
}
