/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionsValidationError
import org.openapitools.client.models.ActionViewOneOf5DeleteKey
import org.openapitools.client.models.ActionsValidationErrorOneOf
import org.openapitools.client.models.ActionsValidationErrorOneOf1
import org.openapitools.client.models.ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf2
import org.openapitools.client.models.ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf3
import org.openapitools.client.models.ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf4
import org.openapitools.client.models.ActionsValidationErrorOneOf4InvalidAccountId
import org.openapitools.client.models.ActionsValidationErrorOneOf5
import org.openapitools.client.models.ActionsValidationErrorOneOf5ContractSizeExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf6
import org.openapitools.client.models.ActionsValidationErrorOneOf7
import org.openapitools.client.models.ActionsValidationErrorOneOf8
import org.openapitools.client.models.ActionsValidationErrorOneOf9
import org.openapitools.client.models.ActionsValidationErrorOneOf9UnsupportedProtocolFeature
import org.openapitools.client.models.ActionsValidationErrorOneOfTotalPrepaidGasExceeded

class ActionsValidationErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionsValidationError
        //val modelInstance = ActionsValidationError()

        // to test the property `totalPrepaidGasExceeded`
        should("test totalPrepaidGasExceeded") {
            // uncomment below to test the property
            //modelInstance.totalPrepaidGasExceeded shouldBe ("TODO")
        }

        // to test the property `totalNumberOfActionsExceeded`
        should("test totalNumberOfActionsExceeded") {
            // uncomment below to test the property
            //modelInstance.totalNumberOfActionsExceeded shouldBe ("TODO")
        }

        // to test the property `addKeyMethodNamesNumberOfBytesExceeded`
        should("test addKeyMethodNamesNumberOfBytesExceeded") {
            // uncomment below to test the property
            //modelInstance.addKeyMethodNamesNumberOfBytesExceeded shouldBe ("TODO")
        }

        // to test the property `addKeyMethodNameLengthExceeded`
        should("test addKeyMethodNameLengthExceeded") {
            // uncomment below to test the property
            //modelInstance.addKeyMethodNameLengthExceeded shouldBe ("TODO")
        }

        // to test the property `invalidAccountId`
        should("test invalidAccountId") {
            // uncomment below to test the property
            //modelInstance.invalidAccountId shouldBe ("TODO")
        }

        // to test the property `contractSizeExceeded`
        should("test contractSizeExceeded") {
            // uncomment below to test the property
            //modelInstance.contractSizeExceeded shouldBe ("TODO")
        }

        // to test the property `functionCallMethodNameLengthExceeded`
        should("test functionCallMethodNameLengthExceeded") {
            // uncomment below to test the property
            //modelInstance.functionCallMethodNameLengthExceeded shouldBe ("TODO")
        }

        // to test the property `functionCallArgumentsLengthExceeded`
        should("test functionCallArgumentsLengthExceeded") {
            // uncomment below to test the property
            //modelInstance.functionCallArgumentsLengthExceeded shouldBe ("TODO")
        }

        // to test the property `unsuitableStakingKey`
        should("test unsuitableStakingKey") {
            // uncomment below to test the property
            //modelInstance.unsuitableStakingKey shouldBe ("TODO")
        }

        // to test the property `unsupportedProtocolFeature`
        should("test unsupportedProtocolFeature") {
            // uncomment below to test the property
            //modelInstance.unsupportedProtocolFeature shouldBe ("TODO")
        }

    }
}
