/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf12
import org.openapitools.client.models.FunctionCallError

class ActionErrorKindOneOf12Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf12
        //val modelInstance = ActionErrorKindOneOf12()

        // to test the property `functionCallError`
        should("test functionCallError") {
            // uncomment below to test the property
            //modelInstance.functionCallError shouldBe ("TODO")
        }

    }
}
