/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionErrorKindOneOf3
import org.openapitools.client.models.ActionErrorKindOneOf3CreateAccountNotAllowed

class ActionErrorKindOneOf3Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionErrorKindOneOf3
        //val modelInstance = ActionErrorKindOneOf3()

        // to test the property `createAccountNotAllowed`
        should("test createAccountNotAllowed") {
            // uncomment below to test the property
            //modelInstance.createAccountNotAllowed shouldBe ("TODO")
        }

    }
}
