/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ActionError
import org.openapitools.client.models.ActionErrorKind

class ActionErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionError
        //val modelInstance = ActionError()

        // to test the property `kind` - The kind of ActionError happened
        should("test kind") {
            // uncomment below to test the property
            //modelInstance.kind shouldBe ("TODO")
        }

        // to test the property `index` - Index of the failed action in the transaction. Action index is not defined if ActionError.kind is `ActionErrorKind::LackBalanceForState`
        should("test index") {
            // uncomment below to test the property
            //modelInstance.index shouldBe ("TODO")
        }

    }
}
