/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AddKeyAction
import org.openapitools.client.models.AccessKey

class AddKeyActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddKeyAction
        //val modelInstance = AddKeyAction()

        // to test the property `accessKey` - An access key with the permission
        should("test accessKey") {
            // uncomment below to test the property
            //modelInstance.accessKey shouldBe ("TODO")
        }

        // to test the property `publicKey` - A public key which will be associated with an access_key
        should("test publicKey") {
            // uncomment below to test the property
            //modelInstance.publicKey shouldBe ("TODO")
        }

    }
}
