/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BlockHeaderView
import org.openapitools.client.models.BlockHeaderViewApprovalsInner
import org.openapitools.client.models.SlashedValidator
import org.openapitools.client.models.ValidatorStakeView

class BlockHeaderViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockHeaderView
        //val modelInstance = BlockHeaderView()

        // to test the property `approvals`
        should("test approvals") {
            // uncomment below to test the property
            //modelInstance.approvals shouldBe ("TODO")
        }

        // to test the property `blockMerkleRoot`
        should("test blockMerkleRoot") {
            // uncomment below to test the property
            //modelInstance.blockMerkleRoot shouldBe ("TODO")
        }

        // to test the property `challengesResult`
        should("test challengesResult") {
            // uncomment below to test the property
            //modelInstance.challengesResult shouldBe ("TODO")
        }

        // to test the property `challengesRoot`
        should("test challengesRoot") {
            // uncomment below to test the property
            //modelInstance.challengesRoot shouldBe ("TODO")
        }

        // to test the property `chunkHeadersRoot`
        should("test chunkHeadersRoot") {
            // uncomment below to test the property
            //modelInstance.chunkHeadersRoot shouldBe ("TODO")
        }

        // to test the property `chunkMask`
        should("test chunkMask") {
            // uncomment below to test the property
            //modelInstance.chunkMask shouldBe ("TODO")
        }

        // to test the property `chunkReceiptsRoot`
        should("test chunkReceiptsRoot") {
            // uncomment below to test the property
            //modelInstance.chunkReceiptsRoot shouldBe ("TODO")
        }

        // to test the property `chunkTxRoot`
        should("test chunkTxRoot") {
            // uncomment below to test the property
            //modelInstance.chunkTxRoot shouldBe ("TODO")
        }

        // to test the property `chunksIncluded`
        should("test chunksIncluded") {
            // uncomment below to test the property
            //modelInstance.chunksIncluded shouldBe ("TODO")
        }

        // to test the property `epochId`
        should("test epochId") {
            // uncomment below to test the property
            //modelInstance.epochId shouldBe ("TODO")
        }

        // to test the property `gasPrice`
        should("test gasPrice") {
            // uncomment below to test the property
            //modelInstance.gasPrice shouldBe ("TODO")
        }

        // to test the property `hash`
        should("test hash") {
            // uncomment below to test the property
            //modelInstance.hash shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `lastDsFinalBlock`
        should("test lastDsFinalBlock") {
            // uncomment below to test the property
            //modelInstance.lastDsFinalBlock shouldBe ("TODO")
        }

        // to test the property `lastFinalBlock`
        should("test lastFinalBlock") {
            // uncomment below to test the property
            //modelInstance.lastFinalBlock shouldBe ("TODO")
        }

        // to test the property `latestProtocolVersion`
        should("test latestProtocolVersion") {
            // uncomment below to test the property
            //modelInstance.latestProtocolVersion shouldBe ("TODO")
        }

        // to test the property `nextBpHash`
        should("test nextBpHash") {
            // uncomment below to test the property
            //modelInstance.nextBpHash shouldBe ("TODO")
        }

        // to test the property `nextEpochId`
        should("test nextEpochId") {
            // uncomment below to test the property
            //modelInstance.nextEpochId shouldBe ("TODO")
        }

        // to test the property `outcomeRoot`
        should("test outcomeRoot") {
            // uncomment below to test the property
            //modelInstance.outcomeRoot shouldBe ("TODO")
        }

        // to test the property `prevHash` - The hash of the previous Block
        should("test prevHash") {
            // uncomment below to test the property
            //modelInstance.prevHash shouldBe ("TODO")
        }

        // to test the property `prevStateRoot`
        should("test prevStateRoot") {
            // uncomment below to test the property
            //modelInstance.prevStateRoot shouldBe ("TODO")
        }

        // to test the property `randomValue`
        should("test randomValue") {
            // uncomment below to test the property
            //modelInstance.randomValue shouldBe ("TODO")
        }

        // to test the property `rentPaid` - TODO(2271): deprecated.
        should("test rentPaid") {
            // uncomment below to test the property
            //modelInstance.rentPaid shouldBe ("TODO")
        }

        // to test the property `signature` - Signature of the block producer.
        should("test signature") {
            // uncomment below to test the property
            //modelInstance.signature shouldBe ("TODO")
        }

        // to test the property `timestamp` - Legacy json number. Should not be used.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `timestampNanosec`
        should("test timestampNanosec") {
            // uncomment below to test the property
            //modelInstance.timestampNanosec shouldBe ("TODO")
        }

        // to test the property `totalSupply`
        should("test totalSupply") {
            // uncomment below to test the property
            //modelInstance.totalSupply shouldBe ("TODO")
        }

        // to test the property `validatorProposals`
        should("test validatorProposals") {
            // uncomment below to test the property
            //modelInstance.validatorProposals shouldBe ("TODO")
        }

        // to test the property `validatorReward` - TODO(2271): deprecated.
        should("test validatorReward") {
            // uncomment below to test the property
            //modelInstance.validatorReward shouldBe ("TODO")
        }

        // to test the property `blockBodyHash`
        should("test blockBodyHash") {
            // uncomment below to test the property
            //modelInstance.blockBodyHash shouldBe ("TODO")
        }

        // to test the property `blockOrdinal`
        should("test blockOrdinal") {
            // uncomment below to test the property
            //modelInstance.blockOrdinal shouldBe ("TODO")
        }

        // to test the property `chunkEndorsements`
        should("test chunkEndorsements") {
            // uncomment below to test the property
            //modelInstance.chunkEndorsements shouldBe ("TODO")
        }

        // to test the property `epochSyncDataHash`
        should("test epochSyncDataHash") {
            // uncomment below to test the property
            //modelInstance.epochSyncDataHash shouldBe ("TODO")
        }

        // to test the property `prevHeight`
        should("test prevHeight") {
            // uncomment below to test the property
            //modelInstance.prevHeight shouldBe ("TODO")
        }

    }
}
