/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CallFunctionByBlockId
import org.openapitools.client.models.BlockId

class CallFunctionByBlockIdTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CallFunctionByBlockId
        //val modelInstance = CallFunctionByBlockId()

        // to test the property `blockId`
        should("test blockId") {
            // uncomment below to test the property
            //modelInstance.blockId shouldBe ("TODO")
        }

        // to test the property `accountId` - NEAR Account Identifier.  This is a unique, syntactically valid, human-readable account identifier on the NEAR network.  [See the crate-level docs for information about validation.](index.html#account-id-rules)  Also see [Error kind precedence](AccountId#error-kind-precedence).  ## Examples  ``` use near_account_id::AccountId;  let alice: AccountId = \"alice.near\".parse().unwrap();  assert!(\"ƒelicia.near\".parse::<AccountId>().is_err()); // (ƒ is not f) ```
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `argsBase64` - This type is used to mark function arguments.  NOTE: The main reason for this to exist (except the type-safety) is that the value is transparently serialized and deserialized as a base64-encoded string when serde is used (serde_json).
        should("test argsBase64") {
            // uncomment below to test the property
            //modelInstance.argsBase64 shouldBe ("TODO")
        }

        // to test the property `methodName`
        should("test methodName") {
            // uncomment below to test the property
            //modelInstance.methodName shouldBe ("TODO")
        }

        // to test the property `requestType`
        should("test requestType") {
            // uncomment below to test the property
            //modelInstance.requestType shouldBe ("TODO")
        }

    }
}
