/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ChunkDistributionNetworkConfig
import org.openapitools.client.models.ChunkDistributionUris

class ChunkDistributionNetworkConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChunkDistributionNetworkConfig
        //val modelInstance = ChunkDistributionNetworkConfig()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `uris`
        should("test uris") {
            // uncomment below to test the property
            //modelInstance.uris shouldBe ("TODO")
        }

    }
}
