/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ChunkDistributionUris

class ChunkDistributionUrisTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChunkDistributionUris
        //val modelInstance = ChunkDistributionUris()

        // to test the property `get` - URI for pulling chunks from the stream.
        should("test get") {
            // uncomment below to test the property
            //modelInstance.get shouldBe ("TODO")
        }

        // to test the property `set` - URI for publishing chunks to the stream.
        should("test set") {
            // uncomment below to test the property
            //modelInstance.set shouldBe ("TODO")
        }

    }
}
