/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CloudArchivalWriterConfig
import org.openapitools.client.models.CloudStorageConfig
import org.openapitools.client.models.DurationAsStdSchemaProvider

class CloudArchivalWriterConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CloudArchivalWriterConfig
        //val modelInstance = CloudArchivalWriterConfig()

        // to test the property `cloudStorage` - Configures the external storage used by the archival node.
        should("test cloudStorage") {
            // uncomment below to test the property
            //modelInstance.cloudStorage shouldBe ("TODO")
        }

        // to test the property `archiveBlockData` - Determines whether block-related data should be written to cloud storage.
        should("test archiveBlockData") {
            // uncomment below to test the property
            //modelInstance.archiveBlockData shouldBe ("TODO")
        }

        // to test the property `pollingInterval` - Interval at which the system checks for new blocks or chunks to archive.
        should("test pollingInterval") {
            // uncomment below to test the property
            //modelInstance.pollingInterval shouldBe ("TODO")
        }

    }
}
