/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CloudStorageConfig
import org.openapitools.client.models.ExternalStorageLocation

class CloudStorageConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CloudStorageConfig
        //val modelInstance = CloudStorageConfig()

        // to test the property `storage` - The storage to persist the archival data.
        should("test storage") {
            // uncomment below to test the property
            //modelInstance.storage shouldBe ("TODO")
        }

        // to test the property `credentialsFile` - Location of a json file with credentials allowing access to the bucket.
        should("test credentialsFile") {
            // uncomment below to test the property
            //modelInstance.credentialsFile shouldBe ("TODO")
        }

    }
}
