/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError

class CompilationErrorOneOf2WasmerCompileErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompilationErrorOneOf2WasmerCompileError
        //val modelInstance = CompilationErrorOneOf2WasmerCompileError()

        // to test the property `msg`
        should("test msg") {
            // uncomment below to test the property
            //modelInstance.msg shouldBe ("TODO")
        }

    }
}
