/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CompilationError
import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists
import org.openapitools.client.models.CompilationErrorOneOf
import org.openapitools.client.models.CompilationErrorOneOf1
import org.openapitools.client.models.CompilationErrorOneOf2
import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError
import org.openapitools.client.models.PrepareError

class CompilationErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompilationError
        //val modelInstance = CompilationError()

        // to test the property `codeDoesNotExist`
        should("test codeDoesNotExist") {
            // uncomment below to test the property
            //modelInstance.codeDoesNotExist shouldBe ("TODO")
        }

        // to test the property `prepareError`
        should("test prepareError") {
            // uncomment below to test the property
            //modelInstance.prepareError shouldBe ("TODO")
        }

        // to test the property `wasmerCompileError`
        should("test wasmerCompileError") {
            // uncomment below to test the property
            //modelInstance.wasmerCompileError shouldBe ("TODO")
        }

    }
}
