/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CongestionInfoView

class CongestionInfoViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CongestionInfoView
        //val modelInstance = CongestionInfoView()

        // to test the property `allowedShard`
        should("test allowedShard") {
            // uncomment below to test the property
            //modelInstance.allowedShard shouldBe ("TODO")
        }

        // to test the property `bufferedReceiptsGas`
        should("test bufferedReceiptsGas") {
            // uncomment below to test the property
            //modelInstance.bufferedReceiptsGas shouldBe ("TODO")
        }

        // to test the property `delayedReceiptsGas`
        should("test delayedReceiptsGas") {
            // uncomment below to test the property
            //modelInstance.delayedReceiptsGas shouldBe ("TODO")
        }

        // to test the property `receiptBytes`
        should("test receiptBytes") {
            // uncomment below to test the property
            //modelInstance.receiptBytes shouldBe ("TODO")
        }

    }
}
