/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DataChangesByFinality
import org.openapitools.client.models.Finality

class DataChangesByFinalityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DataChangesByFinality
        //val modelInstance = DataChangesByFinality()

        // to test the property `finality`
        should("test finality") {
            // uncomment below to test the property
            //modelInstance.finality shouldBe ("TODO")
        }

        // to test the property `accountIds`
        should("test accountIds") {
            // uncomment below to test the property
            //modelInstance.accountIds shouldBe ("TODO")
        }

        // to test the property `changesType`
        should("test changesType") {
            // uncomment below to test the property
            //modelInstance.changesType shouldBe ("TODO")
        }

        // to test the property `keyPrefixBase64` - This type is used to mark keys (arrays of bytes) that are queried from store.  NOTE: Currently, this type is only used in the view_client and RPC to be able to transparently pretty-serialize the bytes arrays as base64-encoded strings (see `serialize.rs`).
        should("test keyPrefixBase64") {
            // uncomment below to test the property
            //modelInstance.keyPrefixBase64 shouldBe ("TODO")
        }

    }
}
