/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DeleteKeyAction

class DeleteKeyActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteKeyAction
        //val modelInstance = DeleteKeyAction()

        // to test the property `publicKey` - A public key associated with the access_key to be deleted.
        should("test publicKey") {
            // uncomment below to test the property
            //modelInstance.publicKey shouldBe ("TODO")
        }

    }
}
