/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DetailedDebugStatus
import org.openapitools.client.models.BlockStatusView
import org.openapitools.client.models.CatchupStatusView
import org.openapitools.client.models.NetworkInfoView

class DetailedDebugStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DetailedDebugStatus
        //val modelInstance = DetailedDebugStatus()

        // to test the property `blockProductionDelayMillis`
        should("test blockProductionDelayMillis") {
            // uncomment below to test the property
            //modelInstance.blockProductionDelayMillis shouldBe ("TODO")
        }

        // to test the property `catchupStatus`
        should("test catchupStatus") {
            // uncomment below to test the property
            //modelInstance.catchupStatus shouldBe ("TODO")
        }

        // to test the property `currentHeadStatus`
        should("test currentHeadStatus") {
            // uncomment below to test the property
            //modelInstance.currentHeadStatus shouldBe ("TODO")
        }

        // to test the property `currentHeaderHeadStatus`
        should("test currentHeaderHeadStatus") {
            // uncomment below to test the property
            //modelInstance.currentHeaderHeadStatus shouldBe ("TODO")
        }

        // to test the property `networkInfo`
        should("test networkInfo") {
            // uncomment below to test the property
            //modelInstance.networkInfo shouldBe ("TODO")
        }

        // to test the property `syncStatus`
        should("test syncStatus") {
            // uncomment below to test the property
            //modelInstance.syncStatus shouldBe ("TODO")
        }

    }
}
