/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DumpConfig
import org.openapitools.client.models.DurationAsStdSchemaProvider
import org.openapitools.client.models.ExternalStorageLocation

class DumpConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DumpConfig
        //val modelInstance = DumpConfig()

        // to test the property `location` - Specifies where to write the obtained state parts.
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `credentialsFile` - Location of a json file with credentials allowing access to the bucket.
        should("test credentialsFile") {
            // uncomment below to test the property
            //modelInstance.credentialsFile shouldBe ("TODO")
        }

        // to test the property `iterationDelay`
        should("test iterationDelay") {
            // uncomment below to test the property
            //modelInstance.iterationDelay shouldBe ("TODO")
        }

        // to test the property `restartDumpForShards` - Use in case a node that dumps state to the external storage gets in trouble.
        should("test restartDumpForShards") {
            // uncomment below to test the property
            //modelInstance.restartDumpForShards shouldBe ("TODO")
        }

    }
}
