/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExecutionStatusViewOneOf
import org.openapitools.client.models.TxExecutionError

class ExecutionStatusViewOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecutionStatusViewOneOf
        //val modelInstance = ExecutionStatusViewOneOf()

        // to test the property `failure`
        should("test failure") {
            // uncomment below to test the property
            //modelInstance.failure shouldBe ("TODO")
        }

    }
}
