/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExecutionStatusViewOneOf2

class ExecutionStatusViewOneOf2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecutionStatusViewOneOf2
        //val modelInstance = ExecutionStatusViewOneOf2()

        // to test the property `successReceiptId`
        should("test successReceiptId") {
            // uncomment below to test the property
            //modelInstance.successReceiptId shouldBe ("TODO")
        }

    }
}
