/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExecutionOutcomeWithIdView
import org.openapitools.client.models.ExecutionOutcomeView
import org.openapitools.client.models.MerklePathItem

class ExecutionOutcomeWithIdViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecutionOutcomeWithIdView
        //val modelInstance = ExecutionOutcomeWithIdView()

        // to test the property `blockHash`
        should("test blockHash") {
            // uncomment below to test the property
            //modelInstance.blockHash shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `outcome`
        should("test outcome") {
            // uncomment below to test the property
            //modelInstance.outcome shouldBe ("TODO")
        }

        // to test the property `proof`
        should("test proof") {
            // uncomment below to test the property
            //modelInstance.proof shouldBe ("TODO")
        }

    }
}
