/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExecutionMetadataView
import org.openapitools.client.models.CostGasUsed

class ExecutionMetadataViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecutionMetadataView
        //val modelInstance = ExecutionMetadataView()

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `gasProfile`
        should("test gasProfile") {
            // uncomment below to test the property
            //modelInstance.gasProfile shouldBe ("TODO")
        }

    }
}
