/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExternalStorageLocationOneOfS3

class ExternalStorageLocationOneOfS3Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExternalStorageLocationOneOfS3
        //val modelInstance = ExternalStorageLocationOneOfS3()

        // to test the property `bucket` - Location of state dumps on S3.
        should("test bucket") {
            // uncomment below to test the property
            //modelInstance.bucket shouldBe ("TODO")
        }

        // to test the property `region` - Data may only be available in certain locations.
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

    }
}
