/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExternalStorageLocationOneOf2GCS

class ExternalStorageLocationOneOf2GCSTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExternalStorageLocationOneOf2GCS
        //val modelInstance = ExternalStorageLocationOneOf2GCS()

        // to test the property `bucket`
        should("test bucket") {
            // uncomment below to test the property
            //modelInstance.bucket shouldBe ("TODO")
        }

    }
}
