/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExternalStorageLocation
import org.openapitools.client.models.ExternalStorageLocationOneOf
import org.openapitools.client.models.ExternalStorageLocationOneOf1
import org.openapitools.client.models.ExternalStorageLocationOneOf1Filesystem
import org.openapitools.client.models.ExternalStorageLocationOneOf2
import org.openapitools.client.models.ExternalStorageLocationOneOf2GCS
import org.openapitools.client.models.ExternalStorageLocationOneOfS3

class ExternalStorageLocationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExternalStorageLocation
        //val modelInstance = ExternalStorageLocation()

        // to test the property `S3`
        should("test S3") {
            // uncomment below to test the property
            //modelInstance.S3 shouldBe ("TODO")
        }

        // to test the property `filesystem`
        should("test filesystem") {
            // uncomment below to test the property
            //modelInstance.filesystem shouldBe ("TODO")
        }

        // to test the property `GCS`
        should("test GCS") {
            // uncomment below to test the property
            //modelInstance.GCS shouldBe ("TODO")
        }

    }
}
