/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Fee

class FeeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Fee
        //val modelInstance = Fee()

        // to test the property `execution` - Fee for executing the object.
        should("test execution") {
            // uncomment below to test the property
            //modelInstance.execution shouldBe ("TODO")
        }

        // to test the property `sendNotSir` - Fee for sending an object potentially across the shards.
        should("test sendNotSir") {
            // uncomment below to test the property
            //modelInstance.sendNotSir shouldBe ("TODO")
        }

        // to test the property `sendSir` - Fee for sending an object from the sender to itself, guaranteeing that it does not leave the shard.
        should("test sendSir") {
            // uncomment below to test the property
            //modelInstance.sendSir shouldBe ("TODO")
        }

    }
}
