/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FunctionCallErrorOneOf
import org.openapitools.client.models.CompilationError

class FunctionCallErrorOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FunctionCallErrorOneOf
        //val modelInstance = FunctionCallErrorOneOf()

        // to test the property `compilationError`
        should("test compilationError") {
            // uncomment below to test the property
            //modelInstance.compilationError shouldBe ("TODO")
        }

    }
}
