/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FunctionCallAction

class FunctionCallActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FunctionCallAction
        //val modelInstance = FunctionCallAction()

        // to test the property `args`
        should("test args") {
            // uncomment below to test the property
            //modelInstance.args shouldBe ("TODO")
        }

        // to test the property `deposit`
        should("test deposit") {
            // uncomment below to test the property
            //modelInstance.deposit shouldBe ("TODO")
        }

        // to test the property `gas`
        should("test gas") {
            // uncomment below to test the property
            //modelInstance.gas shouldBe ("TODO")
        }

        // to test the property `methodName`
        should("test methodName") {
            // uncomment below to test the property
            //modelInstance.methodName shouldBe ("TODO")
        }

    }
}
