/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FunctionCallError
import org.openapitools.client.models.CompilationError
import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError
import org.openapitools.client.models.FunctionCallErrorOneOf
import org.openapitools.client.models.FunctionCallErrorOneOf1
import org.openapitools.client.models.FunctionCallErrorOneOf2
import org.openapitools.client.models.FunctionCallErrorOneOf3
import org.openapitools.client.models.FunctionCallErrorOneOf4
import org.openapitools.client.models.FunctionCallErrorOneOf5
import org.openapitools.client.models.HostError
import org.openapitools.client.models.MethodResolveError
import org.openapitools.client.models.WasmTrap

class FunctionCallErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FunctionCallError
        //val modelInstance = FunctionCallError()

        // to test the property `compilationError`
        should("test compilationError") {
            // uncomment below to test the property
            //modelInstance.compilationError shouldBe ("TODO")
        }

        // to test the property `linkError`
        should("test linkError") {
            // uncomment below to test the property
            //modelInstance.linkError shouldBe ("TODO")
        }

        // to test the property `methodResolveError`
        should("test methodResolveError") {
            // uncomment below to test the property
            //modelInstance.methodResolveError shouldBe ("TODO")
        }

        // to test the property `wasmTrap`
        should("test wasmTrap") {
            // uncomment below to test the property
            //modelInstance.wasmTrap shouldBe ("TODO")
        }

        // to test the property `hostError`
        should("test hostError") {
            // uncomment below to test the property
            //modelInstance.hostError shouldBe ("TODO")
        }

        // to test the property `executionError`
        should("test executionError") {
            // uncomment below to test the property
            //modelInstance.executionError shouldBe ("TODO")
        }

    }
}
