/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FunctionCallErrorOneOf4
import org.openapitools.client.models.HostError

class FunctionCallErrorOneOf4Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of FunctionCallErrorOneOf4
        //val modelInstance = FunctionCallErrorOneOf4()

        // to test the property `hostError`
        should("test hostError") {
            // uncomment below to test the property
            //modelInstance.hostError shouldBe ("TODO")
        }

    }
}
