/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GCConfig
import org.openapitools.client.models.DurationAsStdSchemaProvider

class GCConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GCConfig
        //val modelInstance = GCConfig()

        // to test the property `gcBlocksLimit` - Maximum number of blocks to garbage collect at every garbage collection call.
        should("test gcBlocksLimit") {
            // uncomment below to test the property
            //modelInstance.gcBlocksLimit shouldBe ("TODO")
        }

        // to test the property `gcForkCleanStep` - Maximum number of height to go through at each garbage collection step when cleaning forks during garbage collection.
        should("test gcForkCleanStep") {
            // uncomment below to test the property
            //modelInstance.gcForkCleanStep shouldBe ("TODO")
        }

        // to test the property `gcNumEpochsToKeep` - Number of epochs for which we keep store data.
        should("test gcNumEpochsToKeep") {
            // uncomment below to test the property
            //modelInstance.gcNumEpochsToKeep shouldBe ("TODO")
        }

        // to test the property `gcStepPeriod` - How often gc should be run
        should("test gcStepPeriod") {
            // uncomment below to test the property
            //modelInstance.gcStepPeriod shouldBe ("TODO")
        }

    }
}
