/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf18
import org.openapitools.client.models.CompilationErrorOneOf2WasmerCompileError

class HostErrorOneOf18Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf18
        //val modelInstance = HostErrorOneOf18()

        // to test the property `altBn128InvalidInput`
        should("test altBn128InvalidInput") {
            // uncomment below to test the property
            //modelInstance.altBn128InvalidInput shouldBe ("TODO")
        }

    }
}
