/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf7
import org.openapitools.client.models.HostErrorOneOf7ProhibitedInView

class HostErrorOneOf7Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf7
        //val modelInstance = HostErrorOneOf7()

        // to test the property `prohibitedInView`
        should("test prohibitedInView") {
            // uncomment below to test the property
            //modelInstance.prohibitedInView shouldBe ("TODO")
        }

    }
}
