/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf5
import org.openapitools.client.models.HostErrorOneOf5InvalidReceiptIndex

class HostErrorOneOf5Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf5
        //val modelInstance = HostErrorOneOf5()

        // to test the property `invalidReceiptIndex`
        should("test invalidReceiptIndex") {
            // uncomment below to test the property
            //modelInstance.invalidReceiptIndex shouldBe ("TODO")
        }

    }
}
