/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf5InvalidReceiptIndex

class HostErrorOneOf5InvalidReceiptIndexTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf5InvalidReceiptIndex
        //val modelInstance = HostErrorOneOf5InvalidReceiptIndex()

        // to test the property `receiptIndex`
        should("test receiptIndex") {
            // uncomment below to test the property
            //modelInstance.receiptIndex shouldBe ("TODO")
        }

    }
}
