/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf4
import org.openapitools.client.models.HostErrorOneOf4IteratorWasInvalidated

class HostErrorOneOf4Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf4
        //val modelInstance = HostErrorOneOf4()

        // to test the property `iteratorWasInvalidated`
        should("test iteratorWasInvalidated") {
            // uncomment below to test the property
            //modelInstance.iteratorWasInvalidated shouldBe ("TODO")
        }

    }
}
