/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf10
import org.openapitools.client.models.ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded

class HostErrorOneOf10Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf10
        //val modelInstance = HostErrorOneOf10()

        // to test the property `valueLengthExceeded`
        should("test valueLengthExceeded") {
            // uncomment below to test the property
            //modelInstance.valueLengthExceeded shouldBe ("TODO")
        }

    }
}
