/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf1
import org.openapitools.client.models.HostErrorOneOf1InvalidPromiseIndex

class HostErrorOneOf1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf1
        //val modelInstance = HostErrorOneOf1()

        // to test the property `invalidPromiseIndex`
        should("test invalidPromiseIndex") {
            // uncomment below to test the property
            //modelInstance.invalidPromiseIndex shouldBe ("TODO")
        }

    }
}
