/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf2
import org.openapitools.client.models.HostErrorOneOf2InvalidPromiseResultIndex

class HostErrorOneOf2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf2
        //val modelInstance = HostErrorOneOf2()

        // to test the property `invalidPromiseResultIndex`
        should("test invalidPromiseResultIndex") {
            // uncomment below to test the property
            //modelInstance.invalidPromiseResultIndex shouldBe ("TODO")
        }

    }
}
