/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HostErrorOneOf8
import org.openapitools.client.models.HostErrorOneOf8NumberOfLogsExceeded

class HostErrorOneOf8Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostErrorOneOf8
        //val modelInstance = HostErrorOneOf8()

        // to test the property `numberOfLogsExceeded`
        should("test numberOfLogsExceeded") {
            // uncomment below to test the property
            //modelInstance.numberOfLogsExceeded shouldBe ("TODO")
        }

    }
}
