/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.InvalidTxErrorOneOf6
import org.openapitools.client.models.InvalidTxErrorOneOf6NotEnoughBalance

class InvalidTxErrorOneOf6Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvalidTxErrorOneOf6
        //val modelInstance = InvalidTxErrorOneOf6()

        // to test the property `notEnoughBalance`
        should("test notEnoughBalance") {
            // uncomment below to test the property
            //modelInstance.notEnoughBalance shouldBe ("TODO")
        }

    }
}
