/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.InvalidTxErrorOneOf11ShardCongested

class InvalidTxErrorOneOf11ShardCongestedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvalidTxErrorOneOf11ShardCongested
        //val modelInstance = InvalidTxErrorOneOf11ShardCongested()

        // to test the property `congestionLevel` - A value between 0 (no congestion) and 1 (max congestion).
        should("test congestionLevel") {
            // uncomment below to test the property
            //modelInstance.congestionLevel shouldBe ("TODO")
        }

        // to test the property `shardId` - The congested shard.
        should("test shardId") {
            // uncomment below to test the property
            //modelInstance.shardId shouldBe ("TODO")
        }

    }
}
