/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.InvalidAccessKeyError
import org.openapitools.client.models.ActionErrorKindOneOf5DeleteKeyDoesNotExist
import org.openapitools.client.models.HostErrorOneOf7ProhibitedInView
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf1
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf1ReceiverMismatch
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf2
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf3
import org.openapitools.client.models.InvalidAccessKeyErrorOneOf3NotEnoughAllowance

class InvalidAccessKeyErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvalidAccessKeyError
        //val modelInstance = InvalidAccessKeyError()

        // to test the property `accessKeyNotFound`
        should("test accessKeyNotFound") {
            // uncomment below to test the property
            //modelInstance.accessKeyNotFound shouldBe ("TODO")
        }

        // to test the property `receiverMismatch`
        should("test receiverMismatch") {
            // uncomment below to test the property
            //modelInstance.receiverMismatch shouldBe ("TODO")
        }

        // to test the property `methodNameMismatch`
        should("test methodNameMismatch") {
            // uncomment below to test the property
            //modelInstance.methodNameMismatch shouldBe ("TODO")
        }

        // to test the property `notEnoughAllowance`
        should("test notEnoughAllowance") {
            // uncomment below to test the property
            //modelInstance.notEnoughAllowance shouldBe ("TODO")
        }

    }
}
