/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.InvalidTxErrorOneOf7LackBalanceForState

class InvalidTxErrorOneOf7LackBalanceForStateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvalidTxErrorOneOf7LackBalanceForState
        //val modelInstance = InvalidTxErrorOneOf7LackBalanceForState()

        // to test the property `amount` - Required balance to cover the state.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `signerId` - An account which doesn't have enough balance to cover storage.
        should("test signerId") {
            // uncomment below to test the property
            //modelInstance.signerId shouldBe ("TODO")
        }

    }
}
