/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.JsonRpcResponseForArrayOfRangeOfUint64AndRpcErrorOneOf
import org.openapitools.client.models.RangeOfUint64

class JsonRpcResponseForArrayOfRangeOfUint64AndRpcErrorOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JsonRpcResponseForArrayOfRangeOfUint64AndRpcErrorOneOf
        //val modelInstance = JsonRpcResponseForArrayOfRangeOfUint64AndRpcErrorOneOf()

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

    }
}
