/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.JsonRpcResponseForRpcStateChangesInBlockByTypeResponseAndRpcError
import org.openapitools.client.models.JsonRpcResponseForArrayOfRangeOfUint64AndRpcErrorOneOf1
import org.openapitools.client.models.JsonRpcResponseForRpcStateChangesInBlockByTypeResponseAndRpcErrorOneOf
import org.openapitools.client.models.RpcError
import org.openapitools.client.models.RpcStateChangesInBlockByTypeResponse

class JsonRpcResponseForRpcStateChangesInBlockByTypeResponseAndRpcErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JsonRpcResponseForRpcStateChangesInBlockByTypeResponseAndRpcError
        //val modelInstance = JsonRpcResponseForRpcStateChangesInBlockByTypeResponseAndRpcError()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `jsonrpc`
        should("test jsonrpc") {
            // uncomment below to test the property
            //modelInstance.jsonrpc shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
