/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.JsonRpcRequestForClientConfig
import org.openapitools.client.models.RpcClientConfigRequest

class JsonRpcRequestForClientConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JsonRpcRequestForClientConfig
        //val modelInstance = JsonRpcRequestForClientConfig()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `jsonrpc`
        should("test jsonrpc") {
            // uncomment below to test the property
            //modelInstance.jsonrpc shouldBe ("TODO")
        }

        // to test the property `method`
        should("test method") {
            // uncomment below to test the property
            //modelInstance.method shouldBe ("TODO")
        }

        // to test the property `params`
        should("test params") {
            // uncomment below to test the property
            //modelInstance.params shouldBe ("TODO")
        }

    }
}
