/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.JsonRpcResponseForRpcStateChangesInBlockResponseAndRpcErrorOneOf
import org.openapitools.client.models.RpcStateChangesInBlockResponse

class JsonRpcResponseForRpcStateChangesInBlockResponseAndRpcErrorOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JsonRpcResponseForRpcStateChangesInBlockResponseAndRpcErrorOneOf
        //val modelInstance = JsonRpcResponseForRpcStateChangesInBlockResponseAndRpcErrorOneOf()

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

    }
}
