/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.MerklePathItem
import org.openapitools.client.models.Direction

class MerklePathItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerklePathItem
        //val modelInstance = MerklePathItem()

        // to test the property `direction`
        should("test direction") {
            // uncomment below to test the property
            //modelInstance.direction shouldBe ("TODO")
        }

        // to test the property `hash`
        should("test hash") {
            // uncomment below to test the property
            //modelInstance.hash shouldBe ("TODO")
        }

    }
}
