/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.NetworkInfoView
import org.openapitools.client.models.AccountDataView
import org.openapitools.client.models.KnownProducerView
import org.openapitools.client.models.PeerInfoView

class NetworkInfoViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NetworkInfoView
        //val modelInstance = NetworkInfoView()

        // to test the property `connectedPeers`
        should("test connectedPeers") {
            // uncomment below to test the property
            //modelInstance.connectedPeers shouldBe ("TODO")
        }

        // to test the property `knownProducers`
        should("test knownProducers") {
            // uncomment below to test the property
            //modelInstance.knownProducers shouldBe ("TODO")
        }

        // to test the property `numConnectedPeers`
        should("test numConnectedPeers") {
            // uncomment below to test the property
            //modelInstance.numConnectedPeers shouldBe ("TODO")
        }

        // to test the property `peerMaxCount`
        should("test peerMaxCount") {
            // uncomment below to test the property
            //modelInstance.peerMaxCount shouldBe ("TODO")
        }

        // to test the property `tier1AccountsData`
        should("test tier1AccountsData") {
            // uncomment below to test the property
            //modelInstance.tier1AccountsData shouldBe ("TODO")
        }

        // to test the property `tier1AccountsKeys`
        should("test tier1AccountsKeys") {
            // uncomment below to test the property
            //modelInstance.tier1AccountsKeys shouldBe ("TODO")
        }

        // to test the property `tier1Connections`
        should("test tier1Connections") {
            // uncomment below to test the property
            //modelInstance.tier1Connections shouldBe ("TODO")
        }

    }
}
