/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.NonDelegateAction
import org.openapitools.client.models.AddKeyAction
import org.openapitools.client.models.DeleteAccountAction
import org.openapitools.client.models.DeleteKeyAction
import org.openapitools.client.models.DeployContractAction
import org.openapitools.client.models.DeployGlobalContractAction
import org.openapitools.client.models.FunctionCallAction
import org.openapitools.client.models.NonDelegateActionOneOf
import org.openapitools.client.models.NonDelegateActionOneOf1
import org.openapitools.client.models.NonDelegateActionOneOf2
import org.openapitools.client.models.NonDelegateActionOneOf3
import org.openapitools.client.models.NonDelegateActionOneOf4
import org.openapitools.client.models.NonDelegateActionOneOf5
import org.openapitools.client.models.NonDelegateActionOneOf6
import org.openapitools.client.models.NonDelegateActionOneOf7
import org.openapitools.client.models.NonDelegateActionOneOf8
import org.openapitools.client.models.NonDelegateActionOneOf9
import org.openapitools.client.models.StakeAction
import org.openapitools.client.models.TransferAction
import org.openapitools.client.models.UseGlobalContractAction

class NonDelegateActionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NonDelegateAction
        //val modelInstance = NonDelegateAction()

        // to test the property `createAccount` - Create account action
        should("test createAccount") {
            // uncomment below to test the property
            //modelInstance.createAccount shouldBe ("TODO")
        }

        // to test the property `deployContract`
        should("test deployContract") {
            // uncomment below to test the property
            //modelInstance.deployContract shouldBe ("TODO")
        }

        // to test the property `functionCall`
        should("test functionCall") {
            // uncomment below to test the property
            //modelInstance.functionCall shouldBe ("TODO")
        }

        // to test the property `transfer`
        should("test transfer") {
            // uncomment below to test the property
            //modelInstance.transfer shouldBe ("TODO")
        }

        // to test the property `stake`
        should("test stake") {
            // uncomment below to test the property
            //modelInstance.stake shouldBe ("TODO")
        }

        // to test the property `addKey`
        should("test addKey") {
            // uncomment below to test the property
            //modelInstance.addKey shouldBe ("TODO")
        }

        // to test the property `deleteKey`
        should("test deleteKey") {
            // uncomment below to test the property
            //modelInstance.deleteKey shouldBe ("TODO")
        }

        // to test the property `deleteAccount`
        should("test deleteAccount") {
            // uncomment below to test the property
            //modelInstance.deleteAccount shouldBe ("TODO")
        }

        // to test the property `deployGlobalContract`
        should("test deployGlobalContract") {
            // uncomment below to test the property
            //modelInstance.deployGlobalContract shouldBe ("TODO")
        }

        // to test the property `useGlobalContract`
        should("test useGlobalContract") {
            // uncomment below to test the property
            //modelInstance.useGlobalContract shouldBe ("TODO")
        }

    }
}
