/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.NonDelegateActionOneOf

class NonDelegateActionOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NonDelegateActionOneOf
        //val modelInstance = NonDelegateActionOneOf()

        // to test the property `createAccount` - Create account action
        should("test createAccount") {
            // uncomment below to test the property
            //modelInstance.createAccount shouldBe ("TODO")
        }

    }
}
