/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.NonDelegateActionOneOf7
import org.openapitools.client.models.DeleteAccountAction

class NonDelegateActionOneOf7Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of NonDelegateActionOneOf7
        //val modelInstance = NonDelegateActionOneOf7()

        // to test the property `deleteAccount`
        should("test deleteAccount") {
            // uncomment below to test the property
            //modelInstance.deleteAccount shouldBe ("TODO")
        }

    }
}
