/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptEnumViewOneOf2
import org.openapitools.client.models.ReceiptEnumViewOneOf2GlobalContractDistribution

class ReceiptEnumViewOneOf2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptEnumViewOneOf2
        //val modelInstance = ReceiptEnumViewOneOf2()

        // to test the property `globalContractDistribution`
        should("test globalContractDistribution") {
            // uncomment below to test the property
            //modelInstance.globalContractDistribution shouldBe ("TODO")
        }

    }
}
