/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptValidationError
import org.openapitools.client.models.ActionsValidationError
import org.openapitools.client.models.ActionsValidationErrorOneOf3AddKeyMethodNameLengthExceeded
import org.openapitools.client.models.ActionsValidationErrorOneOf4InvalidAccountId
import org.openapitools.client.models.ActionsValidationErrorOneOf5ContractSizeExceeded
import org.openapitools.client.models.HostErrorOneOf13NumberInputDataDependenciesExceeded
import org.openapitools.client.models.ReceiptValidationErrorOneOf
import org.openapitools.client.models.ReceiptValidationErrorOneOf1
import org.openapitools.client.models.ReceiptValidationErrorOneOf2
import org.openapitools.client.models.ReceiptValidationErrorOneOf3
import org.openapitools.client.models.ReceiptValidationErrorOneOf4
import org.openapitools.client.models.ReceiptValidationErrorOneOf5
import org.openapitools.client.models.ReceiptValidationErrorOneOf6
import org.openapitools.client.models.ReceiptValidationErrorOneOf7

class ReceiptValidationErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptValidationError
        //val modelInstance = ReceiptValidationError()

        // to test the property `invalidPredecessorId`
        should("test invalidPredecessorId") {
            // uncomment below to test the property
            //modelInstance.invalidPredecessorId shouldBe ("TODO")
        }

        // to test the property `invalidReceiverId`
        should("test invalidReceiverId") {
            // uncomment below to test the property
            //modelInstance.invalidReceiverId shouldBe ("TODO")
        }

        // to test the property `invalidSignerId`
        should("test invalidSignerId") {
            // uncomment below to test the property
            //modelInstance.invalidSignerId shouldBe ("TODO")
        }

        // to test the property `invalidDataReceiverId`
        should("test invalidDataReceiverId") {
            // uncomment below to test the property
            //modelInstance.invalidDataReceiverId shouldBe ("TODO")
        }

        // to test the property `returnedValueLengthExceeded`
        should("test returnedValueLengthExceeded") {
            // uncomment below to test the property
            //modelInstance.returnedValueLengthExceeded shouldBe ("TODO")
        }

        // to test the property `numberInputDataDependenciesExceeded`
        should("test numberInputDataDependenciesExceeded") {
            // uncomment below to test the property
            //modelInstance.numberInputDataDependenciesExceeded shouldBe ("TODO")
        }

        // to test the property `actionsValidation`
        should("test actionsValidation") {
            // uncomment below to test the property
            //modelInstance.actionsValidation shouldBe ("TODO")
        }

        // to test the property `receiptSizeExceeded`
        should("test receiptSizeExceeded") {
            // uncomment below to test the property
            //modelInstance.receiptSizeExceeded shouldBe ("TODO")
        }

    }
}
