/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptValidationErrorOneOf5
import org.openapitools.client.models.HostErrorOneOf13NumberInputDataDependenciesExceeded

class ReceiptValidationErrorOneOf5Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptValidationErrorOneOf5
        //val modelInstance = ReceiptValidationErrorOneOf5()

        // to test the property `numberInputDataDependenciesExceeded`
        should("test numberInputDataDependenciesExceeded") {
            // uncomment below to test the property
            //modelInstance.numberInputDataDependenciesExceeded shouldBe ("TODO")
        }

    }
}
