/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptValidationErrorOneOf3
import org.openapitools.client.models.ActionsValidationErrorOneOf4InvalidAccountId

class ReceiptValidationErrorOneOf3Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptValidationErrorOneOf3
        //val modelInstance = ReceiptValidationErrorOneOf3()

        // to test the property `invalidDataReceiverId`
        should("test invalidDataReceiverId") {
            // uncomment below to test the property
            //modelInstance.invalidDataReceiverId shouldBe ("TODO")
        }

    }
}
