/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptEnumViewOneOf
import org.openapitools.client.models.ReceiptEnumViewOneOfAction

class ReceiptEnumViewOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptEnumViewOneOf
        //val modelInstance = ReceiptEnumViewOneOf()

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

    }
}
