/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptEnumViewOneOf2GlobalContractDistribution
import org.openapitools.client.models.GlobalContractIdentifier

class ReceiptEnumViewOneOf2GlobalContractDistributionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptEnumViewOneOf2GlobalContractDistribution
        //val modelInstance = ReceiptEnumViewOneOf2GlobalContractDistribution()

        // to test the property `alreadyDeliveredShards`
        should("test alreadyDeliveredShards") {
            // uncomment below to test the property
            //modelInstance.alreadyDeliveredShards shouldBe ("TODO")
        }

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `targetShard` - The shard identifier. It may be an arbitrary number - it does not need to be a number in the range 0..NUM_SHARDS. The shard ids do not need to be sequential or contiguous.  The shard id is wrapped in a new type to prevent the old pattern of using indices in range 0..NUM_SHARDS and casting to ShardId. Once the transition if fully complete it potentially may be simplified to a regular type alias.
        should("test targetShard") {
            // uncomment below to test the property
            //modelInstance.targetShard shouldBe ("TODO")
        }

    }
}
