/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptEnumViewOneOf1Data

class ReceiptEnumViewOneOf1DataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptEnumViewOneOf1Data
        //val modelInstance = ReceiptEnumViewOneOf1Data()

        // to test the property `dataId`
        should("test dataId") {
            // uncomment below to test the property
            //modelInstance.dataId shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `isPromiseResume`
        should("test isPromiseResume") {
            // uncomment below to test the property
            //modelInstance.isPromiseResume shouldBe ("TODO")
        }

    }
}
