/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptValidationErrorOneOf2
import org.openapitools.client.models.ActionsValidationErrorOneOf4InvalidAccountId

class ReceiptValidationErrorOneOf2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptValidationErrorOneOf2
        //val modelInstance = ReceiptValidationErrorOneOf2()

        // to test the property `invalidSignerId`
        should("test invalidSignerId") {
            // uncomment below to test the property
            //modelInstance.invalidSignerId shouldBe ("TODO")
        }

    }
}
