/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ReceiptValidationErrorOneOf7
import org.openapitools.client.models.ActionsValidationErrorOneOf5ContractSizeExceeded

class ReceiptValidationErrorOneOf7Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReceiptValidationErrorOneOf7
        //val modelInstance = ReceiptValidationErrorOneOf7()

        // to test the property `receiptSizeExceeded`
        should("test receiptSizeExceeded") {
            // uncomment below to test the property
            //modelInstance.receiptSizeExceeded shouldBe ("TODO")
        }

    }
}
