/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcBlockRequest
import org.openapitools.client.models.BlockId
import org.openapitools.client.models.Finality
import org.openapitools.client.models.RpcBlockRequestOneOf
import org.openapitools.client.models.RpcBlockRequestOneOf1
import org.openapitools.client.models.RpcBlockRequestOneOf2
import org.openapitools.client.models.SyncCheckpoint

class RpcBlockRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcBlockRequest
        //val modelInstance = RpcBlockRequest()

        // to test the property `blockId`
        should("test blockId") {
            // uncomment below to test the property
            //modelInstance.blockId shouldBe ("TODO")
        }

        // to test the property `finality`
        should("test finality") {
            // uncomment below to test the property
            //modelInstance.finality shouldBe ("TODO")
        }

        // to test the property `syncCheckpoint`
        should("test syncCheckpoint") {
            // uncomment below to test the property
            //modelInstance.syncCheckpoint shouldBe ("TODO")
        }

    }
}
