/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcCongestionLevelResponse

class RpcCongestionLevelResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcCongestionLevelResponse
        //val modelInstance = RpcCongestionLevelResponse()

        // to test the property `congestionLevel`
        should("test congestionLevel") {
            // uncomment below to test the property
            //modelInstance.congestionLevel shouldBe ("TODO")
        }

    }
}
