/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcChunkResponse
import org.openapitools.client.models.ChunkHeaderView
import org.openapitools.client.models.ReceiptView
import org.openapitools.client.models.SignedTransactionView

class RpcChunkResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcChunkResponse
        //val modelInstance = RpcChunkResponse()

        // to test the property `author` - NEAR Account Identifier.  This is a unique, syntactically valid, human-readable account identifier on the NEAR network.  [See the crate-level docs for information about validation.](index.html#account-id-rules)  Also see [Error kind precedence](AccountId#error-kind-precedence).  ## Examples  ``` use near_account_id::AccountId;  let alice: AccountId = \"alice.near\".parse().unwrap();  assert!(\"ƒelicia.near\".parse::<AccountId>().is_err()); // (ƒ is not f) ```
        should("test author") {
            // uncomment below to test the property
            //modelInstance.author shouldBe ("TODO")
        }

        // to test the property `header`
        should("test header") {
            // uncomment below to test the property
            //modelInstance.header shouldBe ("TODO")
        }

        // to test the property `receipts`
        should("test receipts") {
            // uncomment below to test the property
            //modelInstance.receipts shouldBe ("TODO")
        }

        // to test the property `transactions`
        should("test transactions") {
            // uncomment below to test the property
            //modelInstance.transactions shouldBe ("TODO")
        }

    }
}
