/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcError
import org.openapitools.client.models.RpcErrorOneOf
import org.openapitools.client.models.RpcErrorOneOf1
import org.openapitools.client.models.RpcErrorOneOf2

class RpcErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcError
        //val modelInstance = RpcError()

        // to test the property `code` - Deprecated please use the `error_struct` instead
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `message` - Deprecated please use the `error_struct` instead
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `cause`
        should("test cause") {
            // uncomment below to test the property
            //modelInstance.cause shouldBe ("TODO")
        }

        // to test the property ``data`` - Deprecated please use the `error_struct` instead
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
