/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcLightClientExecutionProofResponse
import org.openapitools.client.models.ExecutionOutcomeWithIdView
import org.openapitools.client.models.LightClientBlockLiteView
import org.openapitools.client.models.MerklePathItem

class RpcLightClientExecutionProofResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcLightClientExecutionProofResponse
        //val modelInstance = RpcLightClientExecutionProofResponse()

        // to test the property `blockHeaderLite`
        should("test blockHeaderLite") {
            // uncomment below to test the property
            //modelInstance.blockHeaderLite shouldBe ("TODO")
        }

        // to test the property `blockProof`
        should("test blockProof") {
            // uncomment below to test the property
            //modelInstance.blockProof shouldBe ("TODO")
        }

        // to test the property `outcomeProof`
        should("test outcomeProof") {
            // uncomment below to test the property
            //modelInstance.outcomeProof shouldBe ("TODO")
        }

        // to test the property `outcomeRootProof`
        should("test outcomeRootProof") {
            // uncomment below to test the property
            //modelInstance.outcomeRootProof shouldBe ("TODO")
        }

    }
}
