/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcLightClientNextBlockRequest

class RpcLightClientNextBlockRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcLightClientNextBlockRequest
        //val modelInstance = RpcLightClientNextBlockRequest()

        // to test the property `lastBlockHash`
        should("test lastBlockHash") {
            // uncomment below to test the property
            //modelInstance.lastBlockHash shouldBe ("TODO")
        }

    }
}
