/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcRequestValidationErrorKindOneOf1
import org.openapitools.client.models.RpcRequestValidationErrorKindOneOf1Info

class RpcRequestValidationErrorKindOneOf1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcRequestValidationErrorKindOneOf1
        //val modelInstance = RpcRequestValidationErrorKindOneOf1()

        // to test the property `info`
        should("test info") {
            // uncomment below to test the property
            //modelInstance.info shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
