/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcRequestValidationErrorKindOneOf1Info

class RpcRequestValidationErrorKindOneOf1InfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcRequestValidationErrorKindOneOf1Info
        //val modelInstance = RpcRequestValidationErrorKindOneOf1Info()

        // to test the property `errorMessage`
        should("test errorMessage") {
            // uncomment below to test the property
            //modelInstance.errorMessage shouldBe ("TODO")
        }

    }
}
