/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcStateChangesInBlockByTypeRequest
import org.openapitools.client.models.AccountChangesByBlockId
import org.openapitools.client.models.AccountChangesByFinality
import org.openapitools.client.models.AccountChangesBySyncCheckpoint
import org.openapitools.client.models.AccountWithPublicKey
import org.openapitools.client.models.AllAccessKeyChangesByBlockId
import org.openapitools.client.models.AllAccessKeyChangesByFinality
import org.openapitools.client.models.AllAccessKeyChangesBySyncCheckpoint
import org.openapitools.client.models.AllGasKeyChangesByBlockId
import org.openapitools.client.models.AllGasKeyChangesByFinality
import org.openapitools.client.models.AllGasKeyChangesBySyncCheckpoint
import org.openapitools.client.models.BlockId
import org.openapitools.client.models.ContractCodeChangesByBlockId
import org.openapitools.client.models.ContractCodeChangesByFinality
import org.openapitools.client.models.ContractCodeChangesBySyncCheckpoint
import org.openapitools.client.models.DataChangesByBlockId
import org.openapitools.client.models.DataChangesByFinality
import org.openapitools.client.models.DataChangesBySyncCheckpoint
import org.openapitools.client.models.Finality
import org.openapitools.client.models.SingleAccessKeyChangesByBlockId
import org.openapitools.client.models.SingleAccessKeyChangesByFinality
import org.openapitools.client.models.SingleAccessKeyChangesBySyncCheckpoint
import org.openapitools.client.models.SingleGasKeyChangesByBlockId
import org.openapitools.client.models.SingleGasKeyChangesByFinality
import org.openapitools.client.models.SingleGasKeyChangesBySyncCheckpoint
import org.openapitools.client.models.SyncCheckpoint

class RpcStateChangesInBlockByTypeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcStateChangesInBlockByTypeRequest
        //val modelInstance = RpcStateChangesInBlockByTypeRequest()

        // to test the property `blockId`
        should("test blockId") {
            // uncomment below to test the property
            //modelInstance.blockId shouldBe ("TODO")
        }

        // to test the property `accountIds`
        should("test accountIds") {
            // uncomment below to test the property
            //modelInstance.accountIds shouldBe ("TODO")
        }

        // to test the property `changesType`
        should("test changesType") {
            // uncomment below to test the property
            //modelInstance.changesType shouldBe ("TODO")
        }

        // to test the property `propertyKeys`
        should("test propertyKeys") {
            // uncomment below to test the property
            //modelInstance.propertyKeys shouldBe ("TODO")
        }

        // to test the property `keyPrefixBase64` - This type is used to mark keys (arrays of bytes) that are queried from store.  NOTE: Currently, this type is only used in the view_client and RPC to be able to transparently pretty-serialize the bytes arrays as base64-encoded strings (see `serialize.rs`).
        should("test keyPrefixBase64") {
            // uncomment below to test the property
            //modelInstance.keyPrefixBase64 shouldBe ("TODO")
        }

        // to test the property `finality`
        should("test finality") {
            // uncomment below to test the property
            //modelInstance.finality shouldBe ("TODO")
        }

        // to test the property `syncCheckpoint`
        should("test syncCheckpoint") {
            // uncomment below to test the property
            //modelInstance.syncCheckpoint shouldBe ("TODO")
        }

    }
}
