/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcSplitStorageInfoResponse

class RpcSplitStorageInfoResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcSplitStorageInfoResponse
        //val modelInstance = RpcSplitStorageInfoResponse()

        // to test the property `coldHeadHeight`
        should("test coldHeadHeight") {
            // uncomment below to test the property
            //modelInstance.coldHeadHeight shouldBe ("TODO")
        }

        // to test the property `finalHeadHeight`
        should("test finalHeadHeight") {
            // uncomment below to test the property
            //modelInstance.finalHeadHeight shouldBe ("TODO")
        }

        // to test the property `headHeight`
        should("test headHeight") {
            // uncomment below to test the property
            //modelInstance.headHeight shouldBe ("TODO")
        }

        // to test the property `hotDbKind`
        should("test hotDbKind") {
            // uncomment below to test the property
            //modelInstance.hotDbKind shouldBe ("TODO")
        }

    }
}
