/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RpcValidatorRequest
import org.openapitools.client.models.BlockId
import org.openapitools.client.models.RpcBlockRequestOneOf
import org.openapitools.client.models.RpcValidatorRequestOneOf

class RpcValidatorRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RpcValidatorRequest
        //val modelInstance = RpcValidatorRequest()

        // to test the property `epochId`
        should("test epochId") {
            // uncomment below to test the property
            //modelInstance.epochId shouldBe ("TODO")
        }

        // to test the property `blockId`
        should("test blockId") {
            // uncomment below to test the property
            //modelInstance.blockId shouldBe ("TODO")
        }

    }
}
