/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ShardLayoutOneOf2
import org.openapitools.client.models.ShardLayoutV2

class ShardLayoutOneOf2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShardLayoutOneOf2
        //val modelInstance = ShardLayoutOneOf2()

        // to test the property `V2`
        should("test V2") {
            // uncomment below to test the property
            //modelInstance.V2 shouldBe ("TODO")
        }

    }
}
