/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ShardLayoutV1

class ShardLayoutV1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShardLayoutV1
        //val modelInstance = ShardLayoutV1()

        // to test the property `boundaryAccounts` - The boundary accounts are the accounts on boundaries between shards. Each shard contains a range of accounts from one boundary account to another - or the smallest or largest account possible. The total number of shards is equal to the number of boundary accounts plus 1.
        should("test boundaryAccounts") {
            // uncomment below to test the property
            //modelInstance.boundaryAccounts shouldBe ("TODO")
        }

        // to test the property `version` - Version of the shard layout, this is useful for uniquely identify the shard layout
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `shardsSplitMap` - Maps shards from the last shard layout to shards that it splits to in this shard layout, Useful for constructing states for the shards. None for the genesis shard layout
        should("test shardsSplitMap") {
            // uncomment below to test the property
            //modelInstance.shardsSplitMap shouldBe ("TODO")
        }

        // to test the property `toParentShardMap` - Maps shard in this shard layout to their parent shard Since shard_ids always range from 0 to num_shards - 1, we use vec instead of a hashmap
        should("test toParentShardMap") {
            // uncomment below to test the property
            //modelInstance.toParentShardMap shouldBe ("TODO")
        }

    }
}
