/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ShardLayoutV0

class ShardLayoutV0Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShardLayoutV0
        //val modelInstance = ShardLayoutV0()

        // to test the property `numShards` - Map accounts evenly across all shards
        should("test numShards") {
            // uncomment below to test the property
            //modelInstance.numShards shouldBe ("TODO")
        }

        // to test the property `version` - Version of the shard layout, this is useful for uniquely identify the shard layout
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

    }
}
