/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SingleAccessKeyChangesBySyncCheckpoint
import org.openapitools.client.models.AccountWithPublicKey
import org.openapitools.client.models.SyncCheckpoint

class SingleAccessKeyChangesBySyncCheckpointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SingleAccessKeyChangesBySyncCheckpoint
        //val modelInstance = SingleAccessKeyChangesBySyncCheckpoint()

        // to test the property `syncCheckpoint`
        should("test syncCheckpoint") {
            // uncomment below to test the property
            //modelInstance.syncCheckpoint shouldBe ("TODO")
        }

        // to test the property `changesType`
        should("test changesType") {
            // uncomment below to test the property
            //modelInstance.changesType shouldBe ("TODO")
        }

        // to test the property `propertyKeys`
        should("test propertyKeys") {
            // uncomment below to test the property
            //modelInstance.propertyKeys shouldBe ("TODO")
        }

    }
}
