/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StateChangeWithCauseViewOneOf7Change

class StateChangeWithCauseViewOneOf7ChangeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StateChangeWithCauseViewOneOf7Change
        //val modelInstance = StateChangeWithCauseViewOneOf7Change()

        // to test the property `accountId` - NEAR Account Identifier.  This is a unique, syntactically valid, human-readable account identifier on the NEAR network.  [See the crate-level docs for information about validation.](index.html#account-id-rules)  Also see [Error kind precedence](AccountId#error-kind-precedence).  ## Examples  ``` use near_account_id::AccountId;  let alice: AccountId = \"alice.near\".parse().unwrap();  assert!(\"ƒelicia.near\".parse::<AccountId>().is_err()); // (ƒ is not f) ```
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `keyBase64` - This type is used to mark keys (arrays of bytes) that are queried from store.  NOTE: Currently, this type is only used in the view_client and RPC to be able to transparently pretty-serialize the bytes arrays as base64-encoded strings (see `serialize.rs`).
        should("test keyBase64") {
            // uncomment below to test the property
            //modelInstance.keyBase64 shouldBe ("TODO")
        }

        // to test the property `valueBase64` - This type is used to mark values returned from store (arrays of bytes).  NOTE: Currently, this type is only used in the view_client and RPC to be able to transparently pretty-serialize the bytes arrays as base64-encoded strings (see `serialize.rs`).
        should("test valueBase64") {
            // uncomment below to test the property
            //modelInstance.valueBase64 shouldBe ("TODO")
        }

    }
}
