/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StateSyncConfig
import org.openapitools.client.models.DumpConfig
import org.openapitools.client.models.SyncConcurrency
import org.openapitools.client.models.SyncConfig

class StateSyncConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StateSyncConfig
        //val modelInstance = StateSyncConfig()

        // to test the property `concurrency`
        should("test concurrency") {
            // uncomment below to test the property
            //modelInstance.concurrency shouldBe ("TODO")
        }

        // to test the property `dump`
        should("test dump") {
            // uncomment below to test the property
            //modelInstance.dump shouldBe ("TODO")
        }

        // to test the property `partsCompressionLvl` - Zstd compression level for state parts.
        should("test partsCompressionLvl") {
            // uncomment below to test the property
            //modelInstance.partsCompressionLvl shouldBe ("TODO")
        }

        // to test the property `sync`
        should("test sync") {
            // uncomment below to test the property
            //modelInstance.sync shouldBe ("TODO")
        }

    }
}
