/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StateChangeWithCauseViewOneOf10
import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists

class StateChangeWithCauseViewOneOf10Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of StateChangeWithCauseViewOneOf10
        //val modelInstance = StateChangeWithCauseViewOneOf10()

        // to test the property `change`
        should("test change") {
            // uncomment below to test the property
            //modelInstance.change shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
