/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StateChangeWithCauseView
import org.openapitools.client.models.ActionErrorKindOneOfAccountAlreadyExists
import org.openapitools.client.models.StateChangeCauseView
import org.openapitools.client.models.StateChangeWithCauseViewOneOf
import org.openapitools.client.models.StateChangeWithCauseViewOneOf1
import org.openapitools.client.models.StateChangeWithCauseViewOneOf10
import org.openapitools.client.models.StateChangeWithCauseViewOneOf2
import org.openapitools.client.models.StateChangeWithCauseViewOneOf3
import org.openapitools.client.models.StateChangeWithCauseViewOneOf4
import org.openapitools.client.models.StateChangeWithCauseViewOneOf5
import org.openapitools.client.models.StateChangeWithCauseViewOneOf6
import org.openapitools.client.models.StateChangeWithCauseViewOneOf7
import org.openapitools.client.models.StateChangeWithCauseViewOneOf8
import org.openapitools.client.models.StateChangeWithCauseViewOneOf9

class StateChangeWithCauseViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StateChangeWithCauseView
        //val modelInstance = StateChangeWithCauseView()

        // to test the property `cause`
        should("test cause") {
            // uncomment below to test the property
            //modelInstance.cause shouldBe ("TODO")
        }

        // to test the property `change`
        should("test change") {
            // uncomment below to test the property
            //modelInstance.change shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
