/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SyncConfig
import org.openapitools.client.models.ExternalStorageConfig
import org.openapitools.client.models.SyncConfigOneOf

class SyncConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SyncConfig
        //val modelInstance = SyncConfig()

        // to test the property `externalStorage`
        should("test externalStorage") {
            // uncomment below to test the property
            //modelInstance.externalStorage shouldBe ("TODO")
        }

    }
}
