/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TrackedShardsConfigOneOf3

class TrackedShardsConfigOneOf3Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrackedShardsConfigOneOf3
        //val modelInstance = TrackedShardsConfigOneOf3()

        // to test the property `accounts`
        should("test accounts") {
            // uncomment below to test the property
            //modelInstance.accounts shouldBe ("TODO")
        }

    }
}
