/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TxExecutionError
import org.openapitools.client.models.ActionError
import org.openapitools.client.models.InvalidTxError
import org.openapitools.client.models.TxExecutionErrorOneOf
import org.openapitools.client.models.TxExecutionErrorOneOf1

class TxExecutionErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TxExecutionError
        //val modelInstance = TxExecutionError()

        // to test the property `actionError`
        should("test actionError") {
            // uncomment below to test the property
            //modelInstance.actionError shouldBe ("TODO")
        }

        // to test the property `invalidTxError`
        should("test invalidTxError") {
            // uncomment below to test the property
            //modelInstance.invalidTxError shouldBe ("TODO")
        }

    }
}
