/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValidatorKickoutReasonOneOf4ProtocolVersionTooOld

class ValidatorKickoutReasonOneOf4ProtocolVersionTooOldTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidatorKickoutReasonOneOf4ProtocolVersionTooOld
        //val modelInstance = ValidatorKickoutReasonOneOf4ProtocolVersionTooOld()

        // to test the property `networkVersion`
        should("test networkVersion") {
            // uncomment below to test the property
            //modelInstance.networkVersion shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

    }
}
