/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValidatorKickoutReasonOneOf2
import org.openapitools.client.models.ValidatorKickoutReasonOneOf2NotEnoughStake

class ValidatorKickoutReasonOneOf2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidatorKickoutReasonOneOf2
        //val modelInstance = ValidatorKickoutReasonOneOf2()

        // to test the property `notEnoughStake`
        should("test notEnoughStake") {
            // uncomment below to test the property
            //modelInstance.notEnoughStake shouldBe ("TODO")
        }

    }
}
