/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Version

class VersionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Version
        //val modelInstance = Version()

        // to test the property `build`
        should("test build") {
            // uncomment below to test the property
            //modelInstance.build shouldBe ("TODO")
        }

        // to test the property `commit`
        should("test commit") {
            // uncomment below to test the property
            //modelInstance.commit shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `rustcVersion`
        should("test rustcVersion") {
            // uncomment below to test the property
            //modelInstance.rustcVersion shouldBe ("TODO")
        }

    }
}
