/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ViewGlobalContractCodeByFinality
import org.openapitools.client.models.Finality

class ViewGlobalContractCodeByFinalityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ViewGlobalContractCodeByFinality
        //val modelInstance = ViewGlobalContractCodeByFinality()

        // to test the property `finality`
        should("test finality") {
            // uncomment below to test the property
            //modelInstance.finality shouldBe ("TODO")
        }

        // to test the property `codeHash`
        should("test codeHash") {
            // uncomment below to test the property
            //modelInstance.codeHash shouldBe ("TODO")
        }

        // to test the property `requestType`
        should("test requestType") {
            // uncomment below to test the property
            //modelInstance.requestType shouldBe ("TODO")
        }

    }
}
